<?php

namespace App\Console\Commands;

use Exception;
use ReflectionClass;
use App\Services\NotificationService;
use App\Events\PaymentSuccess;
use Throwable;
use App\Models\Booking;
use App\Models\Transaction;
use App\Models\User;
use App\Models\WalletTransaction;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

use App\Events\BookingStatusChanged;
use App\Services\UserDebtService;
use App\Services\WalletService;
use App\Http\Controllers\Api\DriverBookingController;

class ProcessAutoCompletedBookings extends Command
{
    protected $signature = 'bookings:process-auto-completed {--delay=20 : Delay in seconds after started}';

    protected $description = 'Process bookings that were auto-started and need to be updated to completed status';

    public function handle()
    {
        $delaySeconds = (int) $this->option('delay');
        $this->info("Processing bookings that were started more than {$delaySeconds} seconds ago...");

        try {
            $processedCount = $this->processAutoCompletedBookings($delaySeconds);

            if ($processedCount > 0) {
                $this->info("Successfully updated {$processedCount} bookings to completed status.");
            } else {
                $this->info("No bookings found to process.");
            }

            return 0;
        } catch (Exception $e) {
            $this->error("Error processing auto-completed bookings: " . $e->getMessage());
            return 1;
        }
    }

    private function processAutoCompletedBookings(int $delaySeconds): int
    {
        // Find bookings that:
        // 1. Are in 'started' status
        // 2. Have a driver assigned
        // 3. Were started more than $delaySeconds ago
        $cutoffTime = now()->subSeconds($delaySeconds);

        $bookings = Booking::where('status', 'started')
            ->whereNotNull('driver_id')
            ->whereNotNull('started_at')
            ->where('started_at', '<=', $cutoffTime)
            ->get();

        if ($bookings->isEmpty()) {
            return 0;
        }

        $processedCount = 0;

        foreach ($bookings as $booking) {
            try {
                DB::transaction(function () use ($booking, &$processedCount) {
                    // Double-check status hasn't changed
                    $booking->refresh();
                    if ($booking->status !== 'started') {
                        return;
                    }

                    // Check if driver is auto-generated driver (only auto-update for auto-generated drivers)
                    $city = $booking->city;
                    if (!$city) {

                        return;
                    }

                    // Extract city name (first part before comma)
                    $cityNameParts = explode(',', $city->name);
                    $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
                    $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

                    // Load driver to check email
                    $booking->load('driver');
                    $driver = $booking->driver;

                    if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                        return;
                    }

                    // Calculate actual distance and duration
                    $actualDistance = $booking->actual_distance ?? $booking->estimated_distance ?? 0;
                    $actualDuration = $booking->actual_duration ?? $booking->estimated_duration ?? 0;

                    // If started_at exists, calculate duration from start time
                    if ($booking->started_at) {
                        $actualDuration = $booking->started_at->diffInMinutes(now());
                    }

                    // Update booking status to completed
                    $booking->update([
                        'status' => 'completed',
                        'completed_at' => now(),
                        'actual_distance' => $actualDistance,
                        'actual_duration' => $actualDuration,
                    ]);

                    // Use existing DriverBookingController methods for fare calculation and trip completion
                    $driverBookingController = app(DriverBookingController::class);

                    // Refresh booking before fare calculation
                    $booking = $booking->fresh();

                    // Calculate and update fare using existing method
                    $reflection = new ReflectionClass($driverBookingController);

                    // Call calculateAndUpdateFare method
                    if ($reflection->hasMethod('calculateAndUpdateFare')) {
                        $calculateFareMethod = $reflection->getMethod('calculateAndUpdateFare');
                        $calculateFareMethod->setAccessible(true);
                        $calculateFareMethod->invoke($driverBookingController, $booking->fresh());
                    }

                    // Process trip completion using reflection to call private method
                    // This creates commission record and processes wallet transactions
                    $booking = $booking->fresh();
                    $booking->loadMissing(['driver.driverProfile', 'rideType']);

                    if ($reflection->hasMethod('processTripCompletion')) {
                        $processTripCompletionMethod = $reflection->getMethod('processTripCompletion');
                        $processTripCompletionMethod->setAccessible(true);
                        $processTripCompletionMethod->invoke($driverBookingController, $booking->fresh());
                    }

                    // Refresh booking after fare calculation
                    $booking = $booking->fresh();

                    // Process payment and update payment_status to 'paid' for all payment methods
                    // IMPORTANT: Do this INSIDE the transaction to ensure it commits
                    $bookingForPayment = $booking->fresh();
                    $paymentMethod = $bookingForPayment->payment_method ?? 'cash';
                    $currentPaymentStatus = $bookingForPayment->payment_status ?? 'pending';



                    if ($paymentMethod === 'cash') {

                        $this->processCashPayment($bookingForPayment, $driver);
                    } else {
                        // For non-cash payments, just update payment_status to 'paid'


                        // Use DB::table to ensure update happens
                        $updated = DB::table('bookings')
                            ->where('id', $bookingForPayment->id)
                            ->update([
                                'payment_status' => 'paid',
                                'updated_at' => now(),
                            ]);



                        // Verify the update
                        $bookingForPayment->refresh();


                        if ($bookingForPayment->payment_status !== 'paid') {
                        } else {
                        }
                    }

                    // Final verification - ensure payment_status is 'paid' in database
                    // This is done INSIDE transaction to ensure it commits
                    $finalDbStatus = DB::table('bookings')
                        ->where('id', $booking->id)
                        ->value('payment_status');

                    if ($finalDbStatus !== 'paid') {


                        // Force update INSIDE transaction
                        DB::table('bookings')
                            ->where('id', $booking->id)
                            ->update([
                                'payment_status' => 'paid',
                                'updated_at' => now(),
                            ]);
                    } else {
                    }

                    // Clear driver's current booking
                    $driver->update(['current_booking_id' => null]);

                    // Update driver profile availability
                    if ($driver->driverProfile) {
                        $driver->driverProfile->update(['is_available' => true]);
                    }

                    $processedCount++;


                    // Refresh and load relationships
                    $booking->refresh();
                    $booking->load(['user', 'driver', 'rideType']);

                    // Send trip completed notification to user (same as normal completion)
                    try {
                        $notificationService = app(NotificationService::class);
                        $notificationService->tripCompleted($booking->fresh());
                    } catch (Exception $e) {
                        // Notification failed, continue processing
                    }

                    // Dispatch event
                    event(new BookingStatusChanged(
                        $booking->fresh(),
                        'completed',
                        'Trip completed successfully (auto-generated driver)'
                    ));
                });

                // Final verification AFTER transaction commit - ensure payment_status is persisted
                $booking->refresh();
                $finalStatusAfterCommit = DB::table('bookings')
                    ->where('id', $booking->id)
                    ->value('payment_status');

                if ($finalStatusAfterCommit !== 'paid') {


                    // Force update OUTSIDE transaction (transaction already committed)
                    DB::table('bookings')
                        ->where('id', $booking->id)
                        ->update([
                            'payment_status' => 'paid',
                            'updated_at' => now(),
                        ]);
                } else {
                    // Payment status is already 'paid'
                }
            } catch (Exception $e) {
                $this->error("Failed to process booking {$booking->id}: " . $e->getMessage());
            }
        }

        return $processedCount;
    }

    /**
     * Process cash payment for auto-generated driver
     * This replicates the logic from PaymentController::updateCashPaymentStatus
     */
    private function processCashPayment(Booking $booking, User $driver): void
    {
        try {


            // Get booking total amount
            $amount = (float) ($booking->total_amount ?? 0);
            $tipAmount = (float) ($booking->tip_amount ?? 0);
            $totalAmount = $amount + $tipAmount;

            if ($totalAmount <= 0) {

                return;
            }

            // Find existing transaction for this booking with cash payment method
            // (transaction might have been created during initTransaction)
            $transaction = Transaction::where('booking_id', $booking->id)
                ->where('payment_method', 'cash')
                ->where('type', 'payment')
                ->orderBy('created_at', 'desc')
                ->first();

            // If transaction doesn't exist, create a new one
            if (!$transaction) {
                $transaction = Transaction::create([
                    'transaction_id' => 'TXN_' . time() . '_' . rand(1000, 9999),
                    'wallet_id' => null,
                    'booking_id' => $booking->id,
                    'user_id' => $booking->user_id,
                    'type' => 'payment',
                    'amount' => $totalAmount,
                    'balance' => 0,
                    'currency' => $booking->currency ?? 'INR',
                    'payment_method' => 'cash',
                    'status' => 'pending', // Will be updated to 'completed' below
                    'description' => "Payment for ride #{$booking->booking_code}",
                    'gateway_transaction_id' => null,
                    'gateway_response' => null,
                    'meta_data' => [
                        'booking_code' => $booking->booking_code,
                        'user_id' => $booking->user_id,
                        'driver_id' => $driver->id,
                        'tip_amount' => $tipAmount,
                        'fare_amount' => $amount,
                        'auto_processed' => true,
                    ],
                ]);
            }

            // Update transaction status to 'completed' (same as updateCashPaymentStatus)
            $transaction->update([
                'status' => 'completed',
                'gateway_response' => [
                    'driver_id' => $driver->id,
                    'driver_name' => $driver->name,
                    'updated_at' => now()->toISOString(),
                    'status' => 'completed',
                    'auto_processed' => true,
                ]
            ]);

            // Clear driver's current_booking_id (same as updateCashPaymentStatus)
            $driver->update([
                'current_booking_id' => null,
            ]);

            // Update booking payment status using DB::table to ensure database update
            $updatedRows = DB::table('bookings')
                ->where('id', $booking->id)
                ->update([
                    'payment_status' => 'paid',
                    'payment_method' => 'cash',
                    'online_paid_amount' => 0,  // Cash payment
                    'total_amount' => $transaction->amount, // Use transaction amount
                    'updated_at' => now(),
                ]);



            // Refresh booking model to get updated values
            $booking->refresh();

            // Settle debts when payment is received (same as updateCashPaymentStatus)
            try {
                app(UserDebtService::class)->settleAppliedDebtsForBooking($booking->fresh());
            } catch (Exception $e) {
                // Debt settlement failed, continue processing
            }

            // Credit debt amount to admin wallet when payment is received (same as updateCashPaymentStatus)
            try {
                $this->creditDebtAmountToAdminWallet($booking->fresh());
            } catch (Exception $e) {
                // Debt credit failed, continue processing
            }

            // Refresh booking and transaction
            $transaction->refresh();
            $booking->refresh();

            // Send payment completion notification to driver (same as updateCashPaymentStatus)
            try {
                app(NotificationService::class)->sendPaymentCompletionNotificationToDriver($booking->fresh());
            } catch (Exception $e) {
                // Notification failed, continue processing
            }

            // Broadcast payment success (same as updateCashPaymentStatus)
            try {
                $this->broadcastPaymentSuccess($transaction);
            } catch (Exception $e) {
                // Broadcast failed, continue processing
            }

            // Final verification - check from DB directly and ensure it's 'paid'
            $finalDbStatus = DB::table('bookings')
                ->where('id', $booking->id)
                ->value('payment_status');

            if ($finalDbStatus !== 'paid') {
                // Force update payment_status to 'paid'
                DB::table('bookings')
                    ->where('id', $booking->id)
                    ->update([
                        'payment_status' => 'paid',
                        'updated_at' => now(),
                    ]);

                // Refresh booking
                $booking->refresh();
                $finalDbStatus = 'paid';
            }
        } catch (Exception $e) {
            // Don't throw - allow booking to complete even if payment processing fails
        }
    }

    /**
     * Broadcast payment success event (same as PaymentController::broadcastPaymentSuccess)
     */
    private function broadcastPaymentSuccess($transaction): void
    {
        try {
            $booking = $transaction->booking;

            if (!$booking) {

                return;
            }

            $metaData = $transaction->meta_data ?? [];
            if (is_string($metaData)) {
                $metaData = json_decode($metaData, true) ?? [];
            }

            if (!empty($metaData['payment_success_broadcasted'])) {

                return;
            }

            broadcast(new PaymentSuccess($transaction, $booking))->toOthers();

            $metaData['payment_success_broadcasted'] = true;
            $metaData['payment_success_broadcasted_at'] = now()->toISOString();
            $transaction->meta_data = $metaData;
            $transaction->save();
        } catch (Exception $e) {
            // Broadcast failed, continue processing
        }
    }

    /**
     * Credit debt amount to admin wallet when payment is received
     * This replicates the logic from PaymentController::creditDebtAmountToAdminWallet
     */
    private function creditDebtAmountToAdminWallet(Booking $booking): void
    {
        try {
            $debtAmount = (float) ($booking->debt_amount ?? 0);

            if ($debtAmount <= 0) {

                return;
            }

            $adminUser = User::find(1);
            if (!$adminUser) {
                // Admin user not found, skip debt credit
                return;
            }

            $walletService = app(WalletService::class);
            $adminWallet = $walletService->ensureWallet($adminUser);

            // Check if debt amount has already been credited for this booking to prevent duplicates
            $existingTransaction = WalletTransaction::where('wallet_id', $adminWallet->id)
                ->where(function ($query) use ($booking, $debtAmount) {
                    $query->where(function ($q) use ($booking, $debtAmount) {
                        $q->where('reference_type', Booking::class)
                            ->where('reference_id', $booking->id);
                    })->orWhere(function ($q) use ($booking, $debtAmount) {
                        $q->whereRaw("JSON_EXTRACT(meta_data, '$.booking_id') = ?", [$booking->id])
                            ->orWhereRaw("JSON_UNQUOTE(JSON_EXTRACT(meta_data, '$.booking_id')) = ?", [$booking->id]);
                    });
                })
                ->where('amount', $debtAmount)
                ->where('description', 'like', '%debt%')
                ->first();

            if ($existingTransaction) {

                return;
            }

            // Determine payment method and whether it's cash
            $paymentMethod = $booking->payment_method ?? 'cash';
            $paymentMethodNormalized = strtolower(trim($paymentMethod));
            $isCashPayment = $paymentMethodNormalized === 'cash';

            // For cash payments ONLY: debit debt amount from driver wallet (driver has the cash)
            if ($isCashPayment && $booking->driver_id) {
                $driver = $booking->driver;
                if ($driver) {
                    $driverWallet = $walletService->ensureWallet($driver);

                    // Check if debt has already been debited from driver wallet
                    $existingDriverDebit = WalletTransaction::where('wallet_id', $driverWallet->id)
                        ->where(function ($query) use ($booking, $debtAmount) {
                            $query->where(function ($q) use ($booking, $debtAmount) {
                                $q->where('reference_type', Booking::class)
                                    ->where('reference_id', $booking->id);
                            })->orWhere(function ($q) use ($booking, $debtAmount) {
                                $q->whereRaw("JSON_EXTRACT(meta_data, '$.booking_id') = ?", [$booking->id])
                                    ->orWhereRaw("JSON_UNQUOTE(JSON_EXTRACT(meta_data, '$.booking_id')) = ?", [$booking->id]);
                            });
                        })
                        ->where('amount', -$debtAmount)
                        ->where('description', 'like', '%debt%')
                        ->first();

                    if (!$existingDriverDebit) {
                        // Debit debt amount from driver wallet
                        $driverDebitTransaction = $driverWallet->debit(
                            $debtAmount,
                            WalletTransaction::TYPE_ADJUSTMENT,
                            "Debt amount deducted for booking #{$booking->booking_code}",
                            [
                                'booking_id' => $booking->id,
                                'booking_code' => $booking->booking_code,
                                'user_id' => $booking->user_id,
                                'debt_amount' => $debtAmount,
                                'payment_method' => 'cash',
                                'debited_at' => now()->toDateTimeString(),
                            ],
                            null,
                            true // Allow negative balance
                        );

                        $driverDebitTransactionId = 'DEBT_DRV_' . time() . '_' . rand(1000, 9999);
                        $driverDebitTransaction->update([
                            'transection_id' => $driverDebitTransactionId,
                            'reference_type' => Booking::class,
                            'reference_id' => $booking->id,
                        ]);
                    }
                }
            }

            // Credit debt amount to admin wallet
            $walletTransaction = $adminWallet->credit(
                $debtAmount,
                WalletTransaction::TYPE_ADJUSTMENT,
                "Debt payment received for booking #{$booking->booking_code}",
                [
                    'booking_id' => $booking->id,
                    'booking_code' => $booking->booking_code,
                    'user_id' => $booking->user_id,
                    'debt_amount' => $debtAmount,
                    'payment_method' => $paymentMethod,
                    'credited_at' => now()->toDateTimeString(),
                ]
            );

            $transactionId = 'DEBT_' . time() . '_' . rand(1000, 9999);
            $walletTransaction->update([
                'transection_id' => $transactionId,
                'reference_type' => Booking::class,
                'reference_id' => $booking->id,
            ]);
        } catch (Throwable $e) {
        }
    }
}
