<?php

namespace App\Console\Commands;

use Exception;
use App\Services\NotificationService;
use App\Models\Booking;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Cache;
use App\Events\BookingStatusChanged;

class ProcessAutoStartedBookings extends Command
{
    protected $signature = 'bookings:process-auto-started {--delay=10 : Delay in seconds after arrival}';

    protected $description = 'Process bookings that were auto-arrived and need to be updated to started status';

    public function handle()
    {
        $delaySeconds = (int) $this->option('delay');
        $this->info("Processing bookings that were arrived more than {$delaySeconds} seconds ago...");

        try {
            $processedCount = $this->processAutoStartedBookings($delaySeconds);

            if ($processedCount > 0) {
                $this->info("Successfully updated {$processedCount} bookings to started status.");
            } else {
                $this->info("No bookings found to process.");
            }

            return 0;
        } catch (Exception $e) {
            $this->error("Error processing auto-started bookings: " . $e->getMessage());
            return 1;
        }
    }

    private function processAutoStartedBookings(int $delaySeconds): int
    {
        // Find bookings that:
        // 1. Are in 'arrived' status
        // 2. Have a driver assigned
        // 3. Were updated (arrived) more than $delaySeconds ago
        $cutoffTime = now()->subSeconds($delaySeconds);

        $bookings = Booking::where('status', 'arrived')
            ->whereNotNull('driver_id')
            ->where('updated_at', '<=', $cutoffTime)
            ->get();

        if ($bookings->isEmpty()) {
            return 0;
        }

        $processedCount = 0;

        foreach ($bookings as $booking) {
            try {
                DB::transaction(function () use ($booking, &$processedCount) {
                    // Double-check status hasn't changed
                    $booking->refresh();
                    if ($booking->status !== 'arrived') {
                        return;
                    }

                    // Check if driver is auto-generated driver (only auto-update for auto-generated drivers)
                    $city = $booking->city;
                    if (!$city) {

                        return;
                    }

                    // Extract city name (first part before comma)
                    $cityNameParts = explode(',', $city->name);
                    $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
                    $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

                    // Load driver to check email
                    $booking->load('driver');
                    $driver = $booking->driver;

                    if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                        return;
                    }

                    // Update to started status (bypass OTP for auto-generated driver)
                    $booking->update([
                        'status' => 'started',
                        'started_at' => now(),
                        'otp_verified_at' => now(), // Mark OTP as verified
                    ]);

                    // Initialize waypoint index for route simulation from pickup to destination
                    $waypointIndexKey = "booking_{$booking->id}_started_waypoint_index";
                    Cache::put($waypointIndexKey, 0, 3600); // Start from waypoint 0

                    $processedCount++;


                    // Refresh and load relationships
                    $booking->refresh();
                    $booking->load(['user', 'driver', 'rideType']);

                    // Send trip started notification to user (same as normal start)
                    try {
                        $notificationService = app(NotificationService::class);
                        $bookingForNotification = $booking->fresh();
                        $bookingForNotification->load(['user', 'driver', 'rideType']);

                        // Use tripStarted() method (same as normal flow)
                        $notificationService->tripStarted($bookingForNotification);
                    } catch (Exception $e) {
                    }

                    // Dispatch event
                    event(new BookingStatusChanged(
                        $booking->fresh(),
                        'started',
                        'OTP verified successfully, trip started (auto-generated driver)'
                    ));

                    // Auto-completed will be handled by ProcessAutoCompletedBookings command
                    // No need to schedule job, command will process it automatically

                });
            } catch (Exception $e) {
                $this->error("Failed to process booking {$booking->id}: " . $e->getMessage());
            }
        }

        return $processedCount;
    }
}
