<?php

namespace App\Console\Commands;

use Exception;
use App\Services\NotificationService;
use App\Jobs\AutoUpdateBookingToStarted;
use App\Models\Booking;
use App\Models\DriverLocation;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

use App\Events\BookingStatusChanged;
use App\Events\DriverLocationUpdatedForBooking;

class ProcessAutoArrivedBookings extends Command
{
    protected $signature = 'bookings:process-auto-arrived {--delay=30 : Delay in seconds after acceptance}';

    protected $description = 'Process bookings that were auto-accepted and need to be updated to arrived status';

    public function handle()
    {
        $delaySeconds = (int) $this->option('delay');
        $this->info("Processing bookings that were accepted more than {$delaySeconds} seconds ago...");

        try {
            $processedCount = $this->processAutoArrivedBookings($delaySeconds);

            if ($processedCount > 0) {
                $this->info("Successfully updated {$processedCount} bookings to arrived status.");
            } else {
                $this->info("No bookings found to process.");
            }

            return 0;
        } catch (Exception $e) {
            $this->error("Error processing auto-arrived bookings: " . $e->getMessage());
            return 1;
        }
    }

    private function processAutoArrivedBookings(int $delaySeconds): int
    {
        // Find bookings that:
        // 1. Are in 'accepted' status
        // 2. Have a driver assigned
        // 3. Were updated (accepted) more than $delaySeconds ago (using updated_at)
        $cutoffTime = now()->subSeconds($delaySeconds);

        $bookings = Booking::where('status', 'accepted')
            ->whereNotNull('driver_id')
            ->where('updated_at', '<=', $cutoffTime)
            ->get();

        if ($bookings->isEmpty()) {
            return 0;
        }

        $processedCount = 0;

        foreach ($bookings as $booking) {
            try {
                DB::transaction(function () use ($booking, &$processedCount) {
                    // Double-check status hasn't changed
                    $booking->refresh();
                    if ($booking->status !== 'accepted') {
                        return;
                    }

                    // Check if driver is auto-generated driver (only auto-update for auto-generated drivers)
                    $city = $booking->city;
                    if (!$city) {

                        return;
                    }

                    // Extract city name (first part before comma)
                    $cityNameParts = explode(',', $city->name);
                    $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
                    $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

                    // Load driver to check email
                    $booking->load('driver');
                    $driver = $booking->driver;

                    if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                        return;
                    }

                    // Update to arrived status
                    // Try to set driver_arrival_time if column exists, otherwise just update status
                    try {
                        $booking->update([
                            'status' => 'arrived',
                            'driver_arrival_time' => now(),
                        ]);
                    } catch (Exception $e) {
                        // Column doesn't exist, just update status
                        $booking->update(['status' => 'arrived']);
                    }

                    // Update driver location to pickup location when arrived
                    if ($booking->driver_id && $booking->pickup_latitude && $booking->pickup_longitude) {
                        $driverLocation = DriverLocation::where('driver_id', $booking->driver_id)
                            ->where('is_active', true)
                            ->first();

                        if ($driverLocation) {
                            $driverLocation->update([
                                'latitude' => $booking->pickup_latitude,
                                'longitude' => $booking->pickup_longitude,
                                'recorded_at' => now(),
                            ]);
                        }

                        // Update driver's last location in users table
                        $booking->driver->update([
                            'last_latitude' => $booking->pickup_latitude,
                            'last_longitude' => $booking->pickup_longitude,
                            'last_location_at' => now(),
                        ]);

                        // Broadcast final location update to pickup
                        event(new DriverLocationUpdatedForBooking(
                            $booking->id,
                            $booking->driver_id,
                            (float) $booking->pickup_latitude,
                            (float) $booking->pickup_longitude,
                            null // No polyline needed when arrived
                        ));
                    }

                    $processedCount++;


                    // Refresh and load relationships
                    $booking->refresh();
                    $booking->load(['user', 'driver']);

                    // Send notification to user
                    $notificationService = app(NotificationService::class);
                    $otp = $booking->otp ?: 'N/A';
                    $message = 'Your driver has arrived. Please provide otp ' . $otp;
                    $notificationService->sendBookingNotificationToUser(
                        $booking,
                        'driver_arrived',
                        $message
                    );



                    // Dispatch event
                    event(new BookingStatusChanged(
                        $booking->fresh(),
                        'arrived',
                        $message
                    ));

                    // Schedule auto-update to 'started' status after 10 seconds (bypass OTP for auto-generated driver)
                    $startDelaySeconds = 10;


                    AutoUpdateBookingToStarted::dispatch($booking->fresh())
                        ->delay(now()->addSeconds($startDelaySeconds));
                });
            } catch (Exception $e) {
                $this->error("Failed to process booking {$booking->id}: " . $e->getMessage());
            }
        }

        return $processedCount;
    }
}
