<?php

namespace App\Console\Commands;

use Exception;
use App\Events\DriverLocationByBookingUpdated;
use App\Models\Booking;
use App\Models\DriverLocation;
use App\Services\GoogleMapsService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Cache;


class UpdateAutoAcceptedDriverLocations extends Command
{
    protected $signature = 'bookings:update-auto-driver-locations {--interval=2 : Update interval in seconds} {--continuous : Run continuously} {--no-continuous : Disable continuous mode (for manual testing)}';

    protected $description = 'Update driver locations for auto-accepted bookings every 2 seconds using 300m waypoints from Google Maps polyline (stops after arrived)';

    public function handle()
    {
        try {
            // Clear optimization caches before each run to ensure fresh config values
            // This is necessary because config cache can cause stale Google Maps API key issues
            try {
                Artisan::call('optimize:clear');
            } catch (Exception $e) {
                // Fallback to just config:clear if optimize:clear fails
                try {
                    Artisan::call('config:clear');
                } catch (Exception $e2) {
                }
            }

            $interval = (int) $this->option('interval');
            $continuous = $this->option('continuous');
            $noContinuous = $this->option('no-continuous');

            // For scheduler: always use fixed duration mode (not continuous) to avoid mutex issues
            // Scheduler runs every minute, so we run for 70 seconds to ensure overlap
            $isSchedulerRun = !$this->input->isInteractive();


            // If explicitly set to continuous (manual run), use continuous mode
            // Otherwise, use fixed duration mode for scheduler reliability
            if ($continuous && !$isSchedulerRun) {
                // Run continuously (only for manual runs)
                while (true) {
                    try {
                        $this->updateDriverLocations();
                    } catch (Exception $e) {
                        // Continue running even if there's an error
                    }
                    sleep($interval);
                }
            } else {
                // Run updates in a loop for 70 seconds (ensures overlap with next scheduler run)
                // Scheduler runs every minute, so this ensures continuous coverage with no gaps
                $maxRunTime = 70; // Run for 70 seconds
                $startTime = time();
                $iterations = 0;

                while ((time() - $startTime) < $maxRunTime) {
                    try {
                        $this->updateDriverLocations();
                        $iterations++;
                    } catch (Exception $e) {
                        // Continue running even if there's an error
                    }

                    // Sleep for interval, but check if we're near the end
                    if ((time() - $startTime) < ($maxRunTime - $interval)) {
                        sleep($interval);
                    } else {
                        break; // Don't sleep if we're near the end
                    }
                }
            }

            return 0;
        } catch (Exception $e) {
            $this->error('Error updating driver locations: ' . $e->getMessage());
            return 1;
        }
    }

    private function updateDriverLocations(): void
    {
        // Find bookings that are accepted (stop updates after arrival)
        $bookings = Booking::where('status', 'accepted')
            ->whereNotNull('driver_id')
            ->whereNotNull('pickup_latitude')
            ->whereNotNull('pickup_longitude')
            ->with(['driver', 'city'])
            ->get();

        if ($bookings->isEmpty()) {
            return;
        }

        $googleMapsService = app(GoogleMapsService::class);

        // Force refresh API key to ensure fresh config is read
        // This prevents stale config cache issues
        $googleMapsService->refreshApiKey();

        // Log API key status for debugging
        if (!$googleMapsService->hasApiKey()) {
            // API key not available
        }

        foreach ($bookings as $booking) {
            try {
                // Only update locations for auto-generated drivers
                $city = $booking->city;
                if (!$city) {
                    continue;
                }

                // Extract city name (first part before comma)
                $cityNameParts = explode(',', $city->name);
                $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
                $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

                // Load driver to check email
                $booking->load('driver');
                $driver = $booking->driver;

                if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                    // Skip if driver is not auto-generated
                    continue;
                }

                // Get driver's current location from driver_locations table
                $driverLocation = DriverLocation::where('driver_id', $booking->driver_id)
                    ->where('is_active', true)
                    ->latest('recorded_at')
                    ->first();

                // Pickup location (destination)
                $pickupLat = (float) $booking->pickup_latitude;
                $pickupLng = (float) $booking->pickup_longitude;

                // For "accepted" status, require existing driver location
                if (!$driverLocation || !$driverLocation->latitude || !$driverLocation->longitude) {
                    // Try to use driver's last location from users table
                    if ($driver && $driver->last_latitude && $driver->last_longitude) {

                        $driverLocation = new DriverLocation();
                        $driverLocation->driver_id = $booking->driver_id;
                        $driverLocation->is_active = true;
                        $driverLocation->latitude = (float) $driver->last_latitude;
                        $driverLocation->longitude = (float) $driver->last_longitude;
                        $driverLocation->recorded_at = now();
                        $driverLocation->save();
                    } else {

                        continue;
                    }
                }

                // Process "accepted" status bookings (updates stop after arrival)
                // Driver's starting location
                $driverStartLat = (float) $driverLocation->latitude;
                $driverStartLng = (float) $driverLocation->longitude;

                // Check if driver is already very close to pickup (within 10 meters)
                $distanceToPickup = $this->haversineDistance($driverStartLat, $driverStartLng, $pickupLat, $pickupLng);
                if ($distanceToPickup < 0.01) {
                    // Driver already at pickup - move them 2-3 km away to simulate coming to pickup
                    // Calculate a point 2.5 km away in a random direction
                    $distanceAway = 2.5; // km
                    $randomAngle = deg2rad(rand(0, 360)); // Random direction

                    // Calculate new starting point (2.5 km away from pickup)
                    $earthRadius = 6371; // km
                    $newLat = asin(sin(deg2rad($pickupLat)) * cos($distanceAway / $earthRadius) +
                        cos(deg2rad($pickupLat)) * sin($distanceAway / $earthRadius) * cos($randomAngle));
                    $newLng = deg2rad($pickupLng) + atan2(
                        sin($randomAngle) * sin($distanceAway / $earthRadius) * cos(deg2rad($pickupLat)),
                        cos($distanceAway / $earthRadius) - sin(deg2rad($pickupLat)) * sin($newLat)
                    );

                    $driverStartLat = rad2deg($newLat);
                    $driverStartLng = rad2deg($newLng);

                    // Update driver location to new starting point
                    $driverLocation->update([
                        'latitude' => $driverStartLat,
                        'longitude' => $driverStartLng,
                        'recorded_at' => now(),
                    ]);

                    $booking->driver->update([
                        'last_latitude' => $driverStartLat,
                        'last_longitude' => $driverStartLng,
                        'last_location_at' => now(),
                    ]);
                }

                // Get or generate waypoints from Google Maps route
                $waypoints = $this->getRouteWaypoints($booking, $googleMapsService, $driverStartLat, $driverStartLng, $pickupLat, $pickupLng);

                if (empty($waypoints)) {
                    // Fallback: simple linear movement if route not available
                    $currentLat = (float) ($booking->driver->last_latitude ?? $driverStartLat);
                    $currentLng = (float) ($booking->driver->last_longitude ?? $driverStartLng);
                    $distanceToPickup = $this->haversineDistance($currentLat, $currentLng, $pickupLat, $pickupLng);

                    if ($distanceToPickup < 0.01) {
                        $newLat = $pickupLat;
                        $newLng = $pickupLng;
                    } else {
                        $moveFactor = 0.15;
                        $newLat = $currentLat + (($pickupLat - $currentLat) * $moveFactor);
                        $newLng = $currentLng + (($pickupLng - $currentLng) * $moveFactor);
                    }
                } else {
                    // Get current waypoint index from cache
                    $waypointIndexKey = "booking_{$booking->id}_waypoint_index";
                    $currentIndex = Cache::get($waypointIndexKey, 0);


                    if ($currentIndex >= count($waypoints)) {
                        // Reached pickup, use pickup location
                        $newLat = $pickupLat;
                        $newLng = $pickupLng;
                    } else {
                        // Move to next waypoint
                        $waypoint = $waypoints[$currentIndex];
                        $newLat = $waypoint['lat'];
                        $newLng = $waypoint['lng'];

                        // Increment index for next update
                        Cache::put($waypointIndexKey, $currentIndex + 1, 3600);
                    }
                }

                // Update driver location in driver_locations table
                $driverLocation->update([
                    'latitude' => $newLat,
                    'longitude' => $newLng,
                    'recorded_at' => now(),
                ]);

                // Update driver's last location in users table
                $booking->driver->update([
                    'last_latitude' => $newLat,
                    'last_longitude' => $newLng,
                    'last_location_at' => now(),
                ]);

                // Broadcast location update (for arrived status, no polyline needed)
                event(new DriverLocationByBookingUpdated(
                    $booking->id,
                    $newLat,
                    $newLng,
                    $booking->driver_id
                ));

                $distanceToPickup = $this->haversineDistance($newLat, $newLng, $pickupLat, $pickupLng);
            } catch (Exception $e) {
                // Continue with next booking
            }
        }
    }

    /**
     * Get route polyline from current driver location to pickup
     */
    private function getRoutePolyline(Booking $booking, GoogleMapsService $googleMapsService, float $currentLat, float $currentLng, float $pickupLat, float $pickupLng): ?string
    {
        $cacheKey = "booking_{$booking->id}_route_polyline_{$currentLat}_{$currentLng}";

        return Cache::remember($cacheKey, 300, function () use ($googleMapsService, $currentLat, $currentLng, $pickupLat, $pickupLng) {
            // Get route with polyline from current location to pickup
            $routeData = $googleMapsService->getDistanceAndDuration($currentLat, $currentLng, $pickupLat, $pickupLng);
            return $routeData['polyline'] ?? null;
        });
    }

    /**
     * Get waypoints every 1 km along Google Maps route
     */
    private function getRouteWaypoints(Booking $booking, GoogleMapsService $googleMapsService, float $startLat, float $startLng, float $endLat, float $endLng): array
    {
        $cacheKey = "booking_{$booking->id}_route_waypoints";

        return Cache::remember($cacheKey, 3600, function () use ($googleMapsService, $startLat, $startLng, $endLat, $endLng) {
            // Get route with steps from Google Maps
            $routeData = $googleMapsService->getRouteWithSteps($startLat, $startLng, $endLat, $endLng);

            if (!$routeData || empty($routeData['steps'])) {
                // Try to decode polyline if available
                if (!empty($routeData['polyline'])) {
                    $points = $googleMapsService->decodePolyline($routeData['polyline']);
                    return $this->extractWaypointsEvery50m($points);
                }
                return [];
            }

            // Extract all points from route steps
            $allPoints = [];
            foreach ($routeData['steps'] as $step) {
                if (!empty($step['polyline']['points'])) {
                    $stepPoints = $googleMapsService->decodePolyline($step['polyline']['points']);
                    $allPoints = array_merge($allPoints, $stepPoints);
                }
            }

            if (empty($allPoints)) {
                return [];
            }

            // Extract waypoints every 150 meters
            return $this->extractWaypointsEvery50m($allPoints);
        });
    }

    /**
     * Extract waypoints every 150 meters along the route
     */
    private function extractWaypointsEvery50m(array $points): array
    {
        if (count($points) < 2) {
            return [];
        }

        $waypoints = [];
        $totalDistance = 0;  // Total distance traveled so far
        $targetDistance = 0.15;  // 150 meters intervals (0.15 km)
        $remainingFromPrevious = 0;  // Remaining distance to next waypoint

        for ($i = 0; $i < count($points) - 1; $i++) {
            $currentPoint = $points[$i];
            $nextPoint = $points[$i + 1];

            $segmentDistance = $this->haversineDistance(
                $currentPoint['lat'],
                $currentPoint['lng'],
                $nextPoint['lat'],
                $nextPoint['lng']
            );

            if ($segmentDistance == 0) {
                continue;
            }

            $distanceToUse = $remainingFromPrevious + $segmentDistance;

            // Generate waypoints along this segment
            while ($distanceToUse >= $targetDistance) {
                // Calculate how far into this segment we need to go
                $distanceNeeded = $targetDistance - $remainingFromPrevious;
                $ratio = $distanceNeeded / $segmentDistance;

                $waypointLat = $currentPoint['lat'] + ($nextPoint['lat'] - $currentPoint['lat']) * $ratio;
                $waypointLng = $currentPoint['lng'] + ($nextPoint['lng'] - $currentPoint['lng']) * $ratio;

                $waypoints[] = [
                    'lat' => $waypointLat,
                    'lng' => $waypointLng,
                ];

                $distanceToUse -= $targetDistance;
                $remainingFromPrevious = 0;
            }

            $remainingFromPrevious = $distanceToUse;
        }

        return $waypoints;
    }

    private function calculateProgress(float $currentLat, float $currentLng, float $startLat, float $startLng, float $endLat, float $endLng): float
    {
        // Calculate distance from start to end
        $totalDistance = $this->haversineDistance($startLat, $startLng, $endLat, $endLng);

        if ($totalDistance == 0) {
            return 1.0;
        }

        // Calculate distance from start to current
        $currentDistance = $this->haversineDistance($startLat, $startLng, $currentLat, $currentLng);

        // Progress (0 = at start, 1 = at end)
        return min(1.0, $currentDistance / $totalDistance);
    }

    private function haversineDistance(float $lat1, float $lon1, float $lat2, float $lon2): float
    {
        $earthRadius = 6371;  // km

        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);

        $a = sin($dLat / 2) * sin($dLat / 2)
            + cos(deg2rad($lat1)) * cos(deg2rad($lat2))
            * sin($dLon / 2) * sin($dLon / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c;
    }
}
