<?php

namespace App\Console\Commands;

use Exception;
use App\Events\DriverLocationByBookingUpdated;
use App\Models\Booking;
use App\Services\GoogleMapsService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Cache;


class UpdateAutoStartedDriverLocations extends Command
{
    protected $signature = 'bookings:update-auto-started-locations {--interval=2 : Update interval in seconds} {--continuous : Run continuously} {--no-continuous : Disable continuous mode (for manual testing)}';

    protected $description = 'Update driver locations for auto-started bookings every 2 seconds using waypoints from pickup to destination (broadcast only, no database save)';

    public function handle()
    {
        try {
            // Clear optimization caches before each run
            try {
                Artisan::call('optimize:clear');
            } catch (Exception $e) {
                try {
                    Artisan::call('config:clear');
                } catch (Exception $e2) {
                }
            }

            $interval = (int) $this->option('interval');
            $continuous = $this->option('continuous');
            $noContinuous = $this->option('no-continuous');

            $isSchedulerRun = !$this->input->isInteractive();


            // If explicitly set to continuous (manual run), use continuous mode
            // Otherwise, use fixed duration mode for scheduler reliability
            if ($continuous && !$isSchedulerRun) {
                // Run continuously (only for manual runs)
                while (true) {
                    try {
                        $this->updateDriverLocations();
                    } catch (Exception $e) {
                        // Continue running even if there's an error
                    }
                    sleep($interval);
                }
            } else {
                // Run updates in a loop for 70 seconds (ensures overlap with next scheduler run)
                $maxRunTime = 70; // Run for 70 seconds
                $startTime = time();
                $iterations = 0;

                while ((time() - $startTime) < $maxRunTime) {
                    try {
                        $this->updateDriverLocations();
                        $iterations++;
                    } catch (Exception $e) {
                        // Continue running even if there's an error
                    }

                    // Sleep for interval, but check if we're near the end
                    if ((time() - $startTime) < ($maxRunTime - $interval)) {
                        sleep($interval);
                    } else {
                        break; // Don't sleep if we're near the end
                    }
                }
            }

            return 0;
        } catch (Exception $e) {
            $this->error('Error updating driver locations: ' . $e->getMessage());
            return 1;
        }
    }

    private function updateDriverLocations(): void
    {
        // Find bookings that are started (stop updates after completion)
        $bookings = Booking::where('status', 'started')
            ->whereNotNull('driver_id')
            ->whereNotNull('pickup_latitude')
            ->whereNotNull('pickup_longitude')
            ->whereNotNull('dropoff_latitude')
            ->whereNotNull('dropoff_longitude')
            ->with(['driver', 'city'])
            ->get();

        if ($bookings->isEmpty()) {
            return;
        }

        $googleMapsService = app(GoogleMapsService::class);

        // Force refresh API key to ensure fresh config is read
        $googleMapsService->refreshApiKey();

        if (!$googleMapsService->hasApiKey()) {
            // API key not available
        }

        foreach ($bookings as $booking) {
            try {
                // Only update locations for auto-generated drivers
                $city = $booking->city;
                if (!$city) {
                    continue;
                }

                // Extract city name (first part before comma)
                $cityNameParts = explode(',', $city->name);
                $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
                $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

                // Load driver to check email
                $booking->load('driver');
                $driver = $booking->driver;

                if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                    // Skip if driver is not auto-generated
                    continue;
                }

                // Pickup location (start point)
                $pickupLat = (float) $booking->pickup_latitude;
                $pickupLng = (float) $booking->pickup_longitude;

                // Destination location (end point)
                $destinationLat = (float) $booking->dropoff_latitude;
                $destinationLng = (float) $booking->dropoff_longitude;

                // Get or generate waypoints from Google Maps route (pickup to destination)
                $waypoints = $this->getRouteWaypoints($booking, $googleMapsService, $pickupLat, $pickupLng, $destinationLat, $destinationLng);

                if (empty($waypoints)) {
                    // Fallback: simple linear movement if route not available
                    $waypointIndexKey = "booking_{$booking->id}_started_waypoint_index";
                    $currentIndex = Cache::get($waypointIndexKey, 0);

                    // Calculate total distance
                    $totalDistance = $this->haversineDistance($pickupLat, $pickupLng, $destinationLat, $destinationLng);

                    // Generate 10 waypoints along the route
                    $numWaypoints = 10;
                    $progress = min(1.0, $currentIndex / $numWaypoints);

                    $newLat = $pickupLat + (($destinationLat - $pickupLat) * $progress);
                    $newLng = $pickupLng + (($destinationLng - $pickupLng) * $progress);

                    // Increment index for next update
                    if ($currentIndex < $numWaypoints) {
                        Cache::put($waypointIndexKey, $currentIndex + 1, 3600);
                    } else {
                        // Reached destination, use destination location
                        $newLat = $destinationLat;
                        $newLng = $destinationLng;
                    }
                } else {
                    // Get current waypoint index from cache
                    $waypointIndexKey = "booking_{$booking->id}_started_waypoint_index";
                    $currentIndex = Cache::get($waypointIndexKey, 0);

                    if ($currentIndex >= count($waypoints)) {
                        // Reached destination, use destination location
                        $newLat = $destinationLat;
                        $newLng = $destinationLng;
                    } else {
                        // Move to next waypoint
                        $waypoint = $waypoints[$currentIndex];
                        $newLat = $waypoint['lat'];
                        $newLng = $waypoint['lng'];

                        // Increment index for next update
                        Cache::put($waypointIndexKey, $currentIndex + 1, 3600);
                    }
                }

                // Broadcast location update via Pusher (NO database save)
                event(new DriverLocationByBookingUpdated(
                    $booking->id,
                    $newLat,
                    $newLng,
                    $booking->driver_id
                ));

                $distanceToDestination = $this->haversineDistance($newLat, $newLng, $destinationLat, $destinationLng);
            } catch (Exception $e) {
                // Continue with next booking
            }
        }
    }

    /**
     * Get waypoints every 150 meters along Google Maps route from pickup to destination
     */
    private function getRouteWaypoints(Booking $booking, GoogleMapsService $googleMapsService, float $startLat, float $startLng, float $endLat, float $endLng): array
    {
        $cacheKey = "booking_{$booking->id}_started_route_waypoints";

        return Cache::remember($cacheKey, 3600, function () use ($googleMapsService, $startLat, $startLng, $endLat, $endLng) {
            // Get route with steps from Google Maps
            $routeData = $googleMapsService->getRouteWithSteps($startLat, $startLng, $endLat, $endLng);

            if (!$routeData || empty($routeData['steps'])) {
                // Try to decode polyline if available
                if (!empty($routeData['polyline'])) {
                    $points = $googleMapsService->decodePolyline($routeData['polyline']);
                    return $this->extractWaypointsEvery50m($points);
                }
                return [];
            }

            // Extract all points from route steps
            $allPoints = [];
            foreach ($routeData['steps'] as $step) {
                if (!empty($step['polyline']['points'])) {
                    $stepPoints = $googleMapsService->decodePolyline($step['polyline']['points']);
                    $allPoints = array_merge($allPoints, $stepPoints);
                }
            }

            if (empty($allPoints)) {
                return [];
            }

            // Extract waypoints every 150 meters
            return $this->extractWaypointsEvery50m($allPoints);
        });
    }

    /**
     * Extract waypoints every 150 meters along the route
     */
    private function extractWaypointsEvery50m(array $points): array
    {
        if (count($points) < 2) {
            return [];
        }

        $waypoints = [];
        $totalDistance = 0;  // Total distance traveled so far
        $targetDistance = 0.15;  // 150 meters intervals (0.15 km)
        $remainingFromPrevious = 0;  // Remaining distance to next waypoint

        for ($i = 0; $i < count($points) - 1; $i++) {
            $currentPoint = $points[$i];
            $nextPoint = $points[$i + 1];

            $segmentDistance = $this->haversineDistance(
                $currentPoint['lat'],
                $currentPoint['lng'],
                $nextPoint['lat'],
                $nextPoint['lng']
            );

            if ($segmentDistance == 0) {
                continue;
            }

            $distanceToUse = $remainingFromPrevious + $segmentDistance;

            // Generate waypoints along this segment
            while ($distanceToUse >= $targetDistance) {
                // Calculate how far into this segment we need to go
                $distanceNeeded = $targetDistance - $remainingFromPrevious;
                $ratio = $distanceNeeded / $segmentDistance;

                $waypointLat = $currentPoint['lat'] + ($nextPoint['lat'] - $currentPoint['lat']) * $ratio;
                $waypointLng = $currentPoint['lng'] + ($nextPoint['lng'] - $currentPoint['lng']) * $ratio;

                $waypoints[] = [
                    'lat' => $waypointLat,
                    'lng' => $waypointLng,
                ];

                $distanceToUse -= $targetDistance;
                $remainingFromPrevious = 0;
            }

            $remainingFromPrevious = $distanceToUse;
        }

        return $waypoints;
    }

    private function haversineDistance(float $lat1, float $lon1, float $lat2, float $lon2): float
    {
        $earthRadius = 6371;  // km

        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);

        $a = sin($dLat / 2) * sin($dLat / 2)
            + cos(deg2rad($lat1)) * cos(deg2rad($lat2))
            * sin($dLon / 2) * sin($dLon / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c;
    }
}
