<?php

namespace App\Services;

use App\Events\NewBooking;
use App\Events\CustomDriverBroadcast;
use App\Events\DriverOfferExpired;
use App\Events\BookingStatusChanged;
use App\Enums\BookingState;
use App\Jobs\FindNearbyDrivers;
use App\Models\Booking;
use Carbon\Carbon;
use App\Models\User;
use Illuminate\Support\Facades\Cache;

use Illuminate\Support\Facades\Event;
use App\Services\FCMService;
use App\Models\DriverSearchSetting;

class DriverNotificationService
{
    protected $offerTimeout = 30; // 30 seconds
    protected $maxDriversPerRound = 3; // Notify 3 drivers at a time
    protected $maxRounds = 3; // Maximum 3 rounds of driver notifications
    protected $fcmService;

    public function __construct(FCMService $fcmService)
    {
        $this->fcmService = $fcmService;
    }


    public function startDriverNotification(Booking $booking): array
    {
        $this->setNotificationRound($booking, 1);

        $this->notifyNextRoundOfDrivers($booking);

        // REMOVED: Automatic auto-assign to auto-generated driver
        // Auto-assign will only happen when explicitly called via API
        // This prevents automatic auto-accept when no drivers are found


        return $this->getNotificationResults($booking);
    }

    /**
     * Check if there are any non-auto-generated drivers available for the booking
     */
    protected function hasNonAutoGeneratedDrivers(Booking $booking): bool
    {
        $city = $booking->city;
        if (!$city) {
            return false;
        }

        // Extract city name (first part before comma) to identify auto-generated driver email pattern
        $cityNameParts = explode(',', $city->name);
        $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
        $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

        // Count non-auto-generated drivers (drivers whose email does NOT match the auto-generated pattern)
        $nonAutoDriversCount = User::where('role_id', 2) // Driver role
            ->where('status', 'active')
            ->where('is_online', 1)
            ->where('city_id', $city->id)
            ->where(function ($query) use ($autoGeneratedEmailPattern) {
                $query->where('email', '!=', $autoGeneratedEmailPattern)
                    ->orWhereNull('email');
            })
            ->whereNull('current_booking_id') // Not currently on a ride
            ->whereHas('vehicles', function ($query) use ($booking) {
                if ($booking->ride_type_id) {
                    $query->where('ride_type_id', $booking->ride_type_id)
                        ->where('status', 'active');
                } else {
                    $query->where('status', 'active');
                }
            })
            ->count();



        return $nonAutoDriversCount > 0;
    }

    /**
     * Find autogenerate driver for the booking's city
     */
    protected function findAutogenerateDriverForCity(Booking $booking): ?User
    {
        $city = $booking->city;
        if (!$city) {

            return null;
        }

        // Extract city name (first part before comma) to identify auto-generated driver email pattern
        $cityNameParts = explode(',', $city->name);
        $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
        $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

        // Find the autogenerate driver for this city
        // For auto-generated drivers, we're more flexible:
        // - Don't require is_online (we'll set it if needed)
        // - Check both users.city_id and driverProfile.city_id
        $autogenerateDriver = User::where('email', $autoGeneratedEmailPattern)
            ->where('role_id', 2) // Driver role
            ->where('status', 'active')
            ->where(function ($query) use ($city) {
                $query->where('city_id', $city->id)
                    ->orWhereHas('driverProfile', function ($q) use ($city) {
                        $q->where('city_id', $city->id);
                    });
            })
            ->first();

        // Ensure auto-generated driver is online (set it if not)
        if ($autogenerateDriver && !$autogenerateDriver->is_online) {

            $autogenerateDriver->update(['is_online' => 1]);
            $autogenerateDriver->refresh();
        }

        if ($autogenerateDriver) {
            // Check if driver has a vehicle matching the ride type
            if ($booking->ride_type_id) {
                $hasMatchingVehicle = $autogenerateDriver->vehicles()
                    ->where('ride_type_id', $booking->ride_type_id)
                    ->where('status', 'active')
                    ->exists();

                if (!$hasMatchingVehicle) {

                    return null;
                }
            }
        } else {
        }

        return $autogenerateDriver;
    }


    public function shouldStartNotification(Booking $booking): bool
    {
        return !is_null($booking->ride_type_id);
    }


    public function notifyNextRoundOfDrivers(Booking $booking): void
    {
        $currentRound = $this->getNotificationRound($booking);

        if ($currentRound > $this->maxRounds) {
            $this->handleNoDriversAccepted($booking);
            return;
        }



        $drivers = $this->findNearbyDrivers($booking, $currentRound);

        if ($drivers->isEmpty()) {
            $this->handleNoDriversFound($booking, $currentRound);
            return;
        }

        foreach ($drivers as $driver) {
            $this->notifyDriver($booking, $driver, $currentRound);
        }

        $this->scheduleTimeoutCheck($booking, $currentRound);
    }


    private function calculateDistance(float $lat1, float $lon1, float $lat2, float $lon2): float
    {
        $earthRadius = 6371; // Earth's radius in kilometers

        $latDelta = deg2rad($lat2 - $lat1);
        $lonDelta = deg2rad($lon2 - $lon1);

        $a = sin($latDelta / 2) * sin($latDelta / 2) +
            cos(deg2rad($lat1)) * cos(deg2rad($lat2)) *
            sin($lonDelta / 2) * sin($lonDelta / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c;
    }


    protected function findNearbyDrivers(Booking $booking, int $round): \Illuminate\Support\Collection
    {
        $searchSetting = DriverSearchSetting::getActive();
        $searchRadiusKm = $searchSetting->getRadiusForRound($round);
        $searchRadius = (int) round($searchRadiusKm * 1000); // meters

        // Check for zone/city mismatch - if pickup_zone_id's city doesn't match booking's city_id, bypass zone filtering
        $shouldBypassZoneFilter = false;
        $cityIdToFilter = $booking->city_id;

        if ($booking->pickup_zone_id) {
            $pickupZone = $booking->pickupZone;
            if ($pickupZone && $pickupZone->city_id != $booking->city_id) {
                $shouldBypassZoneFilter = true;
            }
        }


        $driversQuery = User::query()
            ->drivers()
            ->active()
            ->online() // Only get online drivers
            ->whereNull('current_booking_id') // Exclude drivers already engaged with another booking
            ->whereHas('vehicles', function ($query) use ($booking) {
                $query->where('ride_type_id', $booking->ride_type_id)
                    ->where('status', 'active');
            })
            ->whereHas('currentLocation', function ($query) use ($booking, $searchRadius) {
                $query->where('is_active', true)
                    ->where('recorded_at', '>=', now()->subHours(24)) // More lenient time window
                    ->whereRaw('CAST(latitude AS DECIMAL(10,8)) IS NOT NULL')
                    ->whereRaw('CAST(longitude AS DECIMAL(10,8)) IS NOT NULL');
            });

        // Only filter by city_id if booking has city_id and we're not bypassing zone filter
        // When bypassing (zone mismatch), don't filter by city_id at all to allow drivers from any city
        // Note: We'll also check location-based city matching in PHP after fetching drivers to allow
        // drivers who are physically in the city even if their profile city_id doesn't match
        if ($cityIdToFilter && !$shouldBypassZoneFilter) {
            // Don't filter by city_id in the query - we'll check both profile city_id and location-based city in PHP
            // This allows drivers who are physically in the city even if their profile city_id doesn't match
        } elseif ($shouldBypassZoneFilter) {
            // When bypassing due to zone mismatch, skip city_id filtering completely

        }

        // Only exclude drivers with active offers (pending, rejected, accepted)
        // Don't exclude drivers with expired offers - they can be notified again
        $excludedDriverIds = $this->getExcludedDrivers($booking);


        $drivers = $driversQuery
            ->whereNotIn('id', $excludedDriverIds) // Exclude only drivers with active offers
            ->with(['driverProfile', 'currentLocation', 'vehicles'])
            ->get();


        $cityService = app(\App\Services\CityService::class);

        $drivers = $drivers->filter(function ($driver) use ($booking, $searchRadius, $cityIdToFilter, $shouldBypassZoneFilter, $cityService) {
            if (!$driver->currentLocation) {
                return false;
            }

            // Check distance first
            $distance = $this->calculateDistance(
                (float) $booking->pickup_latitude,
                (float) $booking->pickup_longitude,
                (float) $driver->currentLocation->latitude,
                (float) $driver->currentLocation->longitude
            );

            if ($distance > ($searchRadius / 1000)) {
                return false;
            }

            // Check city_id match if we're filtering by city
            if ($cityIdToFilter && !$shouldBypassZoneFilter) {
                // Option 1: Driver's profile city_id matches
                $profileCityMatches = $driver->driverProfile && $driver->driverProfile->city_id == $cityIdToFilter;

                // Option 2: Driver's current location is in the booking's city
                $locationCityMatches = false;
                if ($driver->currentLocation && $driver->currentLocation->latitude && $driver->currentLocation->longitude) {
                    $nearestCity = $cityService->getNearestCity(
                        (float) $driver->currentLocation->latitude,
                        (float) $driver->currentLocation->longitude,
                        50 // max 50km
                    );
                    $locationCityMatches = $nearestCity && $nearestCity->id == $cityIdToFilter;
                }

                // Allow driver if either profile city or location city matches
                if (!$profileCityMatches && !$locationCityMatches) {
                    return false;
                }
            }

            return true;
        });

        $scoringService = app(\App\Services\AdvancedDriverScoringService::class);

        $isFallback = $drivers->some(function ($driver) {
            return $driver->current_booking_id !== null;
        });


        $rankedDrivers = $isFallback
            ? $scoringService->scoreFallbackDrivers($drivers, $booking)
            : $scoringService->scoreIdleDrivers($drivers, $booking);

        $closestDrivers = $rankedDrivers->take($this->maxDriversPerRound);

        return $closestDrivers;
    }


    protected function notifyDriver(Booking $booking, User $driver, int $round): void
    {
        $this->addNotifiedDriver($booking, $driver->id);

        $offerKey = "booking_offer_{$booking->id}_{$driver->id}";
        Cache::put($offerKey, [
            'round' => $round,
            'expires_at' => now()->addSeconds($this->offerTimeout),
            'status' => 'pending'
        ], now()->addSeconds($this->offerTimeout + 60));

        try {

            Event::dispatch(new NewBooking($booking, $booking->user, $driver));
        } catch (\Exception $e) {
            // Log error silently
        }

        $this->sendPushNotification($driver, $booking);
    }


    public function handleDriverAcceptance(Booking $booking, User $driver): bool
    {
        $offerKey = "booking_offer_{$booking->id}_{$driver->id}";
        $offer = Cache::get($offerKey);

        if (!$offer || $offer['status'] !== 'pending') {

            return false;
        }

        if ($booking->status !== 'searching' || $booking->driver_id) {

            return false;
        }

        try {
            $booking->update([
                'driver_id' => $driver->id,
                'status' => 'accepted',
                'accepted_at' => now()
            ]);

            $this->clearAllOffers($booking);

            Event::dispatch(new \App\Events\DriverAssigned($booking, $driver));


            return true;
        } catch (\Exception $e) {
            // Log error silently
            return false;
        }
    }


    protected function getNotificationResults(Booking $booking): array
    {
        $currentRound = $this->getNotificationRound($booking);
        $notifiedDrivers = $this->getNotifiedDrivers($booking);
        $pendingOffers = $this->getPendingOffers($booking);

        return [
            'current_round' => $currentRound,
            'drivers_notified' => count($notifiedDrivers),
            'driver_ids' => $notifiedDrivers,
            'pending_offers' => count($pendingOffers),
            'booking_status' => $booking->status
        ];
    }


    protected function getPendingOffers(Booking $booking): array
    {
        $pendingOffers = [];

        $notifiedDrivers = $this->getNotifiedDrivers($booking);
        foreach ($notifiedDrivers as $driverId) {
            $offerKey = "booking_offer_{$booking->id}_{$driverId}";
            $offer = Cache::get($offerKey);
            if ($offer && $offer['status'] === 'pending') {
                $pendingOffers[] = $driverId;
            }
        }

        return $pendingOffers;
    }


    public function handleDriverRejection(Booking $booking, User $driver): void
    {
        $offerKey = "booking_offer_{$booking->id}_{$driver->id}";
        $offer = Cache::get($offerKey);

        Cache::put($offerKey, array_merge($offer ?? [], [
            'status' => 'rejected',
            'rejected_at' => now()
        ]), now()->addHours(1));



        $this->checkAndNotifyMoreDrivers($booking);
    }


    public function handleOfferTimeout(Booking $booking, int $round): void
    {


        $booking->refresh();

        if ($booking->status !== 'searching' || $booking->driver_id) {

            return;
        }

        $notifiedDrivers = $this->getNotifiedDrivers($booking);
        foreach ($notifiedDrivers as $driverId) {
            $offerKey = "booking_offer_{$booking->id}_{$driverId}";
            $offer = Cache::get($offerKey);

            if ($offer && isset($offer['round']) && $offer['round'] === $round && $offer['status'] === 'pending') {
                Cache::put($offerKey, [
                    'round' => $round,
                    'status' => 'expired',
                    'expired_at' => now()
                ], now()->addHours(1));
            }
        }

        if ($round >= $this->maxRounds) {
            $this->handleNoDriversAccepted($booking);
            return;
        }

        $this->incrementNotificationRound($booking);

        $newRound = $this->getNotificationRound($booking);
        if (in_array($newRound, [2, 3], true)) {
            try {
                Event::dispatch(new CustomDriverBroadcast(
                    'New ride request (round ' . (string) $newRound . ')',
                    'new.ride.request',
                    $this->buildDriverAllPayload($booking, $newRound)
                ));
            } catch (\Exception $e) {
                // Log error silently
            }
        }

        $this->notifyNextRoundOfDrivers($booking);
    }


    protected function checkAndNotifyMoreDrivers(Booking $booking): void
    {
        $notifiedDrivers = $this->getNotifiedDrivers($booking);
        $currentRound = $this->getNotificationRound($booking);


        if ($currentRound <= $this->maxRounds && count($notifiedDrivers) < ($currentRound * $this->maxDriversPerRound)) {

            $this->notifyNextRoundOfDrivers($booking);
        } elseif ($currentRound < $this->maxRounds) {

            $this->incrementNotificationRound($booking);
            $this->notifyNextRoundOfDrivers($booking);
        } else {

            $this->handleNoDriversAccepted($booking);
        }
    }


    protected function scheduleTimeoutCheck(Booking $booking, int $round): void
    {
        \App\Jobs\CheckOfferTimeout::dispatch($booking, $round)
            ->delay(now()->addSeconds($this->offerTimeout));
    }


    protected function handleNoDriversFound(Booking $booking, int $round): void
    {


        if ($round >= $this->maxRounds) {

            $this->handleNoDriversAccepted($booking);
        } else {

            $this->incrementNotificationRound($booking);

            $newRound = $this->getNotificationRound($booking);
            if (in_array($newRound, [2, 3], true)) {
                try {
                    Event::dispatch(new CustomDriverBroadcast(
                        'New ride request (round ' . (string) $newRound . ')',
                        'new.ride.request',
                        $this->buildDriverAllPayload($booking, $newRound)
                    ));
                } catch (\Exception $e) {
                    // Log error silently
                }
            }
            $this->notifyNextRoundOfDrivers($booking);
        }
    }


    protected function handleNoDriversAccepted(Booking $booking): void
    {
        $booking->refresh();

        if ($booking->status !== 'searching' || $booking->driver_id) {

            return;
        }

        // Auto-assignment will ONLY happen via API endpoint /api/driver/bookings/auto-accept
        // Not automatically when booking expires


        // Final expire check - only expire if still searching and no driver assigned
        $booking->refresh();
        if ($booking->status !== 'searching' || $booking->driver_id) {

            return;
        }



        $booking->update([
            'status' => BookingState::EXPIRED->value,
            'cancelled_at' => now(),
            'cancellation_reason' => 'No drivers available or accepted after all rounds',
            'cancelled_by_type' => 'system'
        ]);

        $this->clearAllOffers($booking);

        event(new BookingStatusChanged(
            $booking,
            BookingState::EXPIRED->value,
            'Booking expired - no drivers accepted'
        ));
    }



    protected function clearAllOffers(Booking $booking): void
    {
        $notifiedDrivers = $this->getNotifiedDrivers($booking);

        foreach ($notifiedDrivers as $driverId) {
            $offerKey = "booking_offer_{$booking->id}_{$driverId}";
            Cache::forget($offerKey);
        }

        Cache::forget("booking_{$booking->id}_notified_drivers");
        Cache::forget("booking_{$booking->id}_notification_round");
    }


    protected function getNotificationRound(Booking $booking): int
    {
        return Cache::get("booking_{$booking->id}_notification_round", 1);
    }


    protected function setNotificationRound(Booking $booking, int $round): void
    {
        Cache::put("booking_{$booking->id}_notification_round", $round, now()->addHours(1));
    }


    protected function incrementNotificationRound(Booking $booking): void
    {
        $currentRound = $this->getNotificationRound($booking);
        $this->setNotificationRound($booking, $currentRound + 1);
    }


    protected function getNotifiedDrivers(Booking $booking): array
    {
        return Cache::get("booking_{$booking->id}_notified_drivers", []);
    }


    /**
     * Get driver IDs that should be excluded from notification
     * Only excludes drivers with pending, rejected, or accepted offers
     * Does NOT exclude drivers with expired offers (they can be notified again)
     */
    protected function getExcludedDrivers(Booking $booking): array
    {
        $excludedDrivers = [];
        $notifiedDrivers = $this->getNotifiedDrivers($booking);

        foreach ($notifiedDrivers as $driverId) {
            $offerKey = "booking_offer_{$booking->id}_{$driverId}";
            $offer = Cache::get($offerKey);

            // Only exclude if offer is pending, rejected, or accepted
            // Don't exclude if expired or offer doesn't exist
            $offerStatus = $offer['status'] ?? null;
            if ($offer && in_array($offerStatus, ['pending', 'rejected', 'accepted'])) {
                $excludedDrivers[] = $driverId;
            } elseif ($offer && $offerStatus === 'expired') {
                // Log that expired drivers are being allowed to be notified again

            }
        }

        return $excludedDrivers;
    }


    protected function addNotifiedDriver(Booking $booking, int $driverId): void
    {
        $notifiedDrivers = $this->getNotifiedDrivers($booking);

        if (!in_array($driverId, $notifiedDrivers)) {
            $notifiedDrivers[] = $driverId;
            Cache::put("booking_{$booking->id}_notified_drivers", $notifiedDrivers, now()->addHours(1));
        }
    }


    protected function sendPushNotification(User $driver, Booking $booking): void
    {
        try {
            // Skip notification if driver is not online
            if (!$driver->is_online || $driver->is_online == 0) {

                return;
            }

            if (!$driver->device_token) {

                return;
            }

            if (!$booking->relationLoaded('user')) {
                $booking->load('user');
            }
            if (!$booking->relationLoaded('rideType')) {
                $booking->load('rideType');
            }

            if (!$driver->relationLoaded('vehicles')) {
                $driver->load('vehicles');
            }
            if (!$driver->relationLoaded('driverProfile')) {
                $driver->load('driverProfile');
            }
            if (!$driver->relationLoaded('currentLocation')) {
                $driver->load('currentLocation');
            }

            $user = $booking->user;
            $vehicle = $driver->vehicles->first();
            $driverLocation = $driver->currentLocation;

            $distanceToCustomer = 0;
            if ($driverLocation && $booking->pickup_latitude && $booking->pickup_longitude) {
                $distanceToCustomer = $this->calculateDistance(
                    (float) $driverLocation->latitude,
                    (float) $driverLocation->longitude,
                    (float) $booking->pickup_latitude,
                    (float) $booking->pickup_longitude
                );
            }
            $etaMinutes = $distanceToCustomer > 0 ? ceil($distanceToCustomer * 2.5) : 0;

            $importantData = [
                'booking_id' => (string) $booking->id,
                'booking_code' => $booking->booking_code,
                'status' => 'new_booking',
                'event_type' => 'new_ride_request',
                'acceptance_timer' => 30,
                'booking' => [
                    'id' => (string) $booking->id,
                    'booking_code' => $booking->booking_code,
                    'user_id' => (string) $booking->user_id,
                    'driver_id' => (string) ($booking->driver_id ?? ($driver->id ?? '')),
                    'city_id' => (string) $booking->city_id,
                    'ride_type_id' => (string) $booking->ride_type_id,
                    'cancel_charge' => $this->getCancellationChargeForBooking($booking),
                    'pickup_latitude' => (string) $booking->pickup_latitude,
                    'pickup_longitude' => (string) $booking->pickup_longitude,
                    'dropoff_latitude' => (string) $booking->dropoff_latitude,
                    'dropoff_longitude' => (string) $booking->dropoff_longitude,

                    'pickup_address' => $booking->pickup_address,
                    'dropoff_address' => $booking->dropoff_address,

                    'status' => $booking->status,
                    'payment_method' => $booking->payment_method,
                    'payment_status' => $booking->payment_status ?? 'pending',

                    'otp' => (string) $booking->otp,
                    'estimated_fare' => (string) $booking->estimated_fare,
                    'final_fare' => (string) ($booking->final_fare ?? $booking->estimated_fare),
                    'trip_code' => (string) $booking->trip_code,
                    'scheduled_at' => $booking->scheduled_at?->toISOString(),
                    'created_at' => $booking->created_at?->toISOString(),

                    'ride_type' => [
                        'id' => (string) ($booking->rideType->id ?? ''),
                        'name' => $booking->rideType->name ?? '',
                        'code' => $booking->rideType->code ?? '',
                        'icon' => $booking->rideType->icon ?? '',
                        'capacity' => (string) ($booking->rideType->capacity ?? ''),
                        'waiting_time_limit' => (string) ($booking->rideType->waiting_time_limit ?? ''),
                        'waiting_charge_per_minute' => (string) ($booking->rideType->waiting_charge_per_minute ?? ''),
                    ],
                ],

                'customer' => [
                    'id' => (string) ($user->id ?? ''),
                    'customer_name' => $user->name ?? '',
                    'phone' => $user->phone ?? '',
                    'country_code' => $user->country_code ?? '+91',
                    'customer_photo' => $user->profile_photo ?? '',
                    'customer_rating' => (float) ($user->rating ?? 0),
                    'distance_to_customer' => round($distanceToCustomer, 2),
                    'eta_to_customer' => (string)$etaMinutes,
                ],
                'driver' => [
                    'id' => (string) $driver->id,
                    'name' => $driver->name,
                    'phone' => $driver->phone,
                    'photo' => $driver->profile_photo ?? '',
                    'rating' => (string) ($driver->driverProfile->rating ?? ""),
                    'total_trips' => (string) $driver->bookingsAsDriver()->count(),
                    'is_online' => (string) ($driver->is_online ?? '1'),
                    'current_latitude' => (string) ($driverLocation->latitude ?? ''),
                    'current_longitude' => (string) ($driverLocation->longitude ?? ''),
                    'vehicle' => [
                        'model' => $vehicle->model ?? '',
                        'make' => $vehicle->make ?? '',
                        'color' => $vehicle->color ?? '',
                        'number_plate' => $vehicle->number_plate ?? '',
                        'year' => (string) ($vehicle->year ?? ''),
                    ],
                ],
                'trip_details' => [
                    'distance' => (string) $booking->distance,
                    'duration' => (string) $booking->duration,
                    'fare' => (string) ($booking->final_fare ?? $booking->estimated_fare),
                    'estimated_fare' => (string) $booking->estimated_fare,
                    'final_fare' => (string) $booking->final_fare,
                    'base_fare' => (string) ($booking->base_fare ?? ''),
                    'distance_fare' => (string) ($booking->distance_fare ?? ''),
                    'time_fare' => (string) ($booking->time_fare ?? ''),
                    'surge_multiplier' => (string) ($booking->surge_multiplier ?? '1.00'),
                    'surge_amount' => (string) ($booking->surge_amount ?? '0'),
                ],
                'pickup' => [
                    'address' => $booking->pickup_address,
                    'latitude' => (string) $booking->pickup_latitude,
                    'longitude' => (string) $booking->pickup_longitude,
                ],
                'dropoff' => [
                    'address' => $booking->dropoff_address,
                    'latitude' => (string) $booking->dropoff_latitude,
                    'longitude' => (string) $booking->dropoff_longitude,
                ],
                'ride_type' => [
                    'id' => (string) ($booking->rideType->id ?? ''),
                    'name' => $booking->rideType->name ?? '',
                    'code' => $booking->rideType->code ?? '',
                    'icon' => $booking->rideType->icon ?? '',
                    'capacity' => (string) ($booking->rideType->capacity ?? ''),
                    'waiting_time_limit' => (string) ($booking->rideType->waiting_time_limit ?? ''),
                    'waiting_charge_per_minute' => (string) ($booking->rideType->waiting_charge_per_minute ?? ''),
                ],
                'timestamp' => now()->toISOString(),
            ];

            $fcmPayload = [
                'type' => 'new_booking',
                'booking_id' => (string) $booking->id,
                'status' => 'new_booking',
                'event_type' => 'new_ride_request',
                'data' => json_encode($importantData, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            ];

            $notification = [
                'title' => 'New Ride Request! 🚕',
                'body' => "You have a new ride request. Fare: ₹" . ($booking->estimated_fare ?: $booking->final_fare ?: '0.00'),
                'icon' => 'ic_notification',
                'sound' => 'default',
            ];

            $fcmResult = $this->fcmService->sendToDevice($driver->device_token, $notification, $fcmPayload);

            if ($fcmResult['success'] ?? false) {
            } else {
            }
        } catch (\Exception $e) {
        }
    }


    protected function buildDriverAllPayload(Booking $booking, int $round): array
    {
        $booking->refresh();

        return [
            'success' => true,
            'message' => 'New ride request (round ' . (string) $round . ')',
            'event_type' => 'new_ride_request',
            'booking_id' => (string) ($booking->id ?? ''),
            'round' => (string) $round,
            'booking' => [
                'id' => (string) ($booking->id ?? ''),
                'user_id' => (string) ($booking->user_id ?? ''),
                'ride_type_id' => (string) ($booking->ride_type_id ?? ''),
                'status' => $booking->status ?? 'searching',
                'pickup_address' => $booking->pickup_address ?? '',
                'pickup_latitude' => (string) ($booking->pickup_latitude ?? ''),
                'pickup_longitude' => (string) ($booking->pickup_longitude ?? ''),
                'dropoff_address' => $booking->dropoff_address ?? '',
                'dropoff_latitude' => (string) ($booking->dropoff_latitude ?? ''),
                'dropoff_longitude' => (string) ($booking->dropoff_longitude ?? ''),
                'estimated_distance' => (string) ($booking->estimated_distance ?? ''),
                'estimated_duration' => (string) ($booking->estimated_duration ?? ''),
                'estimated_fare' => (string) ($booking->estimated_fare ?? ''),
            ],
            'timestamp' => now()->toISOString(),
        ];
    }


    protected function removeEmptyValues(array $array): array
    {
        $result = [];
        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $cleaned = $this->removeEmptyValues($value);
                if (!empty($cleaned)) {
                    $result[$key] = $cleaned;
                }
            } elseif ($value !== '' && $value !== null && $value !== []) {
                $result[$key] = $value;
            }
        }
        return $result;
    }

    protected function getCancellationChargeForBooking(Booking $booking): string
    {
        try {
            $city = \App\Models\City::find($booking->city_id);
            if ($city && $booking->ride_type_id) {
                $cityService = app(\App\Services\CityService::class);
                $policy = $cityService->getCancellationPolicy($city, $booking->ride_type_id);

                if ($policy) {
                    // Use cancellation policy fee (for new bookings, trip amount is 0, so just return fixed fee)
                    return (string) ($policy->cancellation_fee ?? '0');
                }
            }
        } catch (\Exception $e) {
        }

        // Fallback to ride type's cancellation charge if policy not found
        return (string) ($booking->rideType->cancellation_charge ?? '0');
    }
}
