<?php

namespace App\Services;

use App\Models\User;
use App\Models\DriverLocation;
use App\Models\Zone;
use App\Events\DriverLocationAutoUpdate;

use Illuminate\Support\Facades\Cache;

class DriverAutoLocationService
{
    
    public function startAutoLocationUpdates(User $driver): bool
    {
        try {
            // Check if driver using role_id instead of Spatie role
            if ($driver->role_id != 2 || !$driver->is_online) {
                
                return false;
            }

            $cacheKey = "auto_location_driver_{$driver->id}";
            Cache::put($cacheKey, [
                'driver_id' => $driver->id,
                'started_at' => now(),
                'last_update' => now(),
                'update_interval' => 10, // seconds
                'is_active' => true
            ], 3600); // Cache for 1 hour

            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    
    public function stopAutoLocationUpdates(User $driver): bool
    {
        try {
            $cacheKey = "auto_location_driver_{$driver->id}";
            Cache::forget($cacheKey);


            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    
    public function updateDriverLocation(User $driver, array $locationData): ?DriverLocation
    {
        try {
            // 🚫 Autogenerated driver check — HARD STOP
            // Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
            if ($this->isAutogeneratedDriver($driver)) {
                
                return null;
            }

            if (!isset($locationData['latitude']) || !isset($locationData['longitude'])) {

                return null;
            }

            $driverLocation = DriverLocation::where('driver_id', $driver->id)
                ->where('is_active', true)
                ->first();

            if (!$driverLocation) {
                $driverLocation = new DriverLocation();
                $driverLocation->driver_id = $driver->id;
                $driverLocation->is_active = true;
            }

            $driverLocation->latitude = $locationData['latitude'];
            $driverLocation->longitude = $locationData['longitude'];
            $driverLocation->heading = $locationData['heading'] ?? 0;
            $driverLocation->speed = $locationData['speed'] ?? 0;
            $driverLocation->accuracy = $locationData['accuracy'] ?? 10;
            $driverLocation->battery_level = $locationData['battery_level'] ?? null;
            $driverLocation->is_charging = $locationData['is_charging'] ?? false;
            $driverLocation->address = $this->getAddressFromCoordinates(
                $locationData['latitude'],
                $locationData['longitude']
            );
            $driverLocation->recorded_at = now();

            $zone = $this->findZoneForLocation($locationData['latitude'], $locationData['longitude']);
            $driverLocation->zone_id = $zone?->id;

            $driverLocation->save();

            $driver->update([
                'last_latitude' => $locationData['latitude'],
                'last_longitude' => $locationData['longitude'],
                'last_location_at' => now(),
            ]);

            event(new DriverLocationAutoUpdate($driver, $driverLocation));

            $cacheKey = "auto_location_driver_{$driver->id}";
            $cacheData = Cache::get($cacheKey);
            if ($cacheData) {
                $cacheData['last_update'] = now();
                Cache::put($cacheKey, $cacheData, 3600);
            }

            

            return $driverLocation;
        } catch (\Exception $e) {
            return null;
        }
    }

    
    public function getActiveAutoLocationDrivers(): array
    {
        $drivers = [];
        $pattern = "auto_location_driver_*";

        $allOnlineDrivers = User::where('is_online', true)
            ->where('role_id', 2) // drivers only
            ->get();

        foreach ($allOnlineDrivers as $driver) {
            $cacheKey = "auto_location_driver_{$driver->id}";
            $cacheData = Cache::get($cacheKey);

            if ($cacheData && $cacheData['is_active']) {
                $drivers[] = [
                    'driver' => $driver,
                    'cache_data' => $cacheData
                ];
            }
        }

        return $drivers;
    }

    
    public function processAutoLocationUpdates(): int
    {
        $activeDrivers = $this->getActiveAutoLocationDrivers();
        $updatedCount = 0;

        foreach ($activeDrivers as $driverData) {
            $driver = $driverData['driver'];
            $cacheData = $driverData['cache_data'];

            $lastUpdate = $cacheData['last_update'] ?? now()->subMinutes(1);
            $shouldUpdate = now()->diffInSeconds($lastUpdate) >= $cacheData['update_interval'];

            if ($shouldUpdate) {
                $locationData = $this->getDriverCurrentLocation($driver);

                if ($locationData) {
                    $location = $this->updateDriverLocation($driver, $locationData);
                    if ($location) {
                        $updatedCount++;
                    }
                }
            }
        }

        if ($updatedCount > 0) {

        }

        return $updatedCount;
    }

    
    private function getDriverCurrentLocation(User $driver): ?array
    {
        $realtimeLocationKey = "realtime_location_driver_{$driver->id}";
        $realtimeLocation = Cache::get($realtimeLocationKey);

        if ($realtimeLocation) {
            return $realtimeLocation;
        }

        $lastLocation = $driver->currentLocation;
        if ($lastLocation && $driver->last_latitude && $driver->last_longitude) {
            $timeSinceUpdate = now()->diffInSeconds($lastLocation->recorded_at);

            if ($timeSinceUpdate < 30) {
                return [
                    'latitude' => $driver->last_latitude,
                    'longitude' => $driver->last_longitude,
                    'heading' => $lastLocation->heading ?? 0,
                    'speed' => $lastLocation->speed ?? 0,
                    'accuracy' => $lastLocation->accuracy ?? 10,
                    'battery_level' => $lastLocation->battery_level ?? 80,
                    'is_charging' => $lastLocation->is_charging ?? false,
                ];
            }
        }

        if ($driver->last_latitude && $driver->last_longitude) {
            return [
                'latitude' => $driver->last_latitude,
                'longitude' => $driver->last_longitude,
                'heading' => 0,
                'speed' => 0,
                'accuracy' => 10,
                'battery_level' => 80,
                'is_charging' => false,
            ];
        }

        return null;
    }

    
    public function storeRealtimeLocation(User $driver, array $locationData): bool
    {
        try {
            $realtimeLocationKey = "realtime_location_driver_{$driver->id}";

            Cache::put($realtimeLocationKey, $locationData, 60);


            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    
    private function findZoneForLocation(float $latitude, float $longitude): ?Zone
    {
        try {
            return null;
        } catch (\Exception $e) {
            return null;
        }
    }

    
    private function getAddressFromCoordinates(float $latitude, float $longitude): string
    {
        return "Location: {$latitude}, {$longitude}";
    }

    /**
     * Check if driver is autogenerated
     * Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
     * 
     * @param User $driver
     * @return bool
     */
    private function isAutogeneratedDriver(User $driver): bool
    {
        if (!$driver->email) {
            return false;
        }

        // Check if email matches pattern: {cityname}driver@etaxi.com
        // Pattern: any characters followed by "driver@etaxi.com"
        $pattern = '/^.+driver@etaxi\.com$/i';
        
        if (preg_match($pattern, $driver->email)) {
            return true;
        }

        return false;
    }
}
