<?php

namespace App\Services;

use App\Events\DriverLocationUpdated;
use App\Events\TripStatusChanged;
use App\Models\Booking;
use App\Models\DriverLocation;
use App\Models\User;
use Illuminate\Support\Facades\Cache;

use MatanYadaev\EloquentSpatial\Objects\Point;

class RealTimeTripService
{
    
    public function updateDriverLocation(User $driver, float $latitude, float $longitude, float $heading = 0, ?float $speed = null): void
    {
        try {
            // 🚫 Autogenerated driver check — HARD STOP
            // Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
            if ($this->isAutogeneratedDriver($driver)) {
                
                return;
            }

            $location = new Point($latitude, $longitude);

            $driver->update([
                'last_latitude' => $latitude,
                'last_longitude' => $longitude,
                'last_location_at' => now(),
            ]);

            $driverLocation = DriverLocation::updateOrCreate(
                ['driver_id' => $driver->id, 'is_active' => true],
                [
                    'latitude' => $latitude,
                    'longitude' => $longitude,
                    'heading' => $heading,
                    'speed' => $speed ?? 0,
                    'recorded_at' => now(),
                ]
            );

            Cache::put("driver_location_{$driver->id}", [
                'lat' => $latitude,
                'lng' => $longitude,
                'heading' => $heading,
                'speed' => $speed,
                'timestamp' => now()->timestamp
            ], 300); // 5 minutes

            $activeBookings = Booking::where('driver_id', $driver->id)
                ->whereIn('status', ['accepted', 'arrived', 'started'])
                ->get();

            foreach ($activeBookings as $booking) {
                $eta = $this->calculateETA($location, $booking, $speed);

                broadcast(new DriverLocationUpdated($driver, $driverLocation));

                
            }
        } catch (\Exception $e) {
            // Continue on error
        }
    }

    
    public function updateTripStatus(Booking $booking, string $newStatus, array $metadata = []): void
    {
        try {
            $oldStatus = $booking->status;

            $booking->update(['status' => $newStatus]);

            $this->addStatusMetadata($booking, $newStatus, $metadata);

            broadcast(new TripStatusChanged($booking, $oldStatus, $newStatus, $metadata));
        } catch (\Exception $e) {
        }
    }

    
    public function getTripInfo(Booking $booking): array
    {
        $tripInfo = [
            'booking_id' => $booking->id,
            'status' => $booking->status,
            'pickup_location' => [
                'address' => $booking->pickup_address,
                'coordinates' => [
                    'lat' => $booking->pickup_location->latitude,
                    'lng' => $booking->pickup_location->longitude,
                ]
            ],
            'drop_location' => [
                'address' => $booking->drop_address,
                'coordinates' => [
                    'lat' => $booking->drop_location->latitude,
                    'lng' => $booking->drop_location->longitude,
                ]
            ],
            'estimated_fare' => $booking->estimated_fare,
            'estimated_duration' => $booking->estimated_duration,
            'estimated_distance' => $booking->estimated_distance,
            'time_info' => $this->getTimeInfo($booking),
        ];

        if ($booking->driver_id) {
            $driver = $booking->driver;
            $driverLocation = Cache::get("driver_location_{$driver->id}");

            $tripInfo['driver'] = [
                'id' => $driver->id,
                'name' => $driver->name,
                'phone' => $driver->phone,
                'rating' => $driver->driverProfile->rating ?? 0,
                'vehicle' => $driver->vehicles()
                    ->where('ride_type_id', $booking->ride_type_id)
                    ->where('status', 'active')
                    ->first()
                    ->only(['model', 'number', 'color']) ?? null,
                'photo' => $this->getImageUrl($driver->profile_photo),
                'current_location' => $driverLocation,
                'eta_to_pickup' => $driverLocation ? $this->calculateETA(
                    new Point($driverLocation['lat'], $driverLocation['lng']),
                    $booking
                ) : null
            ];
        }

        if (in_array($booking->status, ['started', 'completed'])) {
            $tripInfo['trip_progress'] = [
                'start_time' => $booking->trip_start_time,
                'current_duration' => $booking->trip_start_time ? now()->diffInSeconds($booking->trip_start_time) : 0,
                'current_distance' => $this->calculateCurrentDistance($booking)
            ];
        }

        return $tripInfo;
    }

    
    private function getTimeInfo(Booking $booking): array
    {
        return [
            'total_trip_duration' => $this->calculateTotalTripDuration($booking),
            'waiting_time' => $booking->waiting_time ?? 0,
            'total_waiting_time' => $booking->total_waiting_time ?? 0,
            'driver_arrival_time' => $booking->driver_arrival_time ? $booking->driver_arrival_time->toISOString() : '',
            'pickup_time' => $booking->pickup_time ? $booking->pickup_time->toISOString() : '',
            'dropoff_time' => $booking->dropoff_time ? $booking->dropoff_time->toISOString() : '',
            'time_breakdown' => $this->getTimeBreakdown($booking),
        ];
    }

    
    private function calculateTotalTripDuration(Booking $booking): int
    {
        if (!$booking->started_at || !$booking->completed_at) {
            return 0;
        }

        return $booking->started_at->diffInMinutes($booking->completed_at);
    }

    
    private function getTimeBreakdown(Booking $booking): array
    {
        $breakdown = [
            'estimated_vs_actual' => [
                'estimated_duration' => $booking->estimated_duration ?? 0,
                'actual_duration' => $booking->actual_duration ?? 0,
                'duration_difference' => 0,
            ],
            'waiting_times' => [
                'driver_waiting_time' => $booking->waiting_time ?? 0,
                'total_waiting_time' => $booking->total_waiting_time ?? 0,
            ],
            'trip_phases' => [
                'booking_to_driver_assigned' => $this->calculatePhaseDuration($booking->created_at, $booking->driver_arrival_time),
                'driver_arrival_to_pickup' => $this->calculatePhaseDuration($booking->driver_arrival_time, $booking->pickup_time),
                'pickup_to_dropoff' => $this->calculatePhaseDuration($booking->pickup_time, $booking->dropoff_time),
                'total_trip_time' => $this->calculateTotalTripDuration($booking),
            ]
        ];

        if ($booking->estimated_duration && $booking->actual_duration) {
            $breakdown['estimated_vs_actual']['duration_difference'] = $booking->actual_duration - $booking->estimated_duration;
        }

        return $breakdown;
    }

    
    private function calculatePhaseDuration($startTime, $endTime): int
    {
        if (!$startTime || !$endTime) {
            return 0;
        }

        if ($startTime instanceof \Carbon\Carbon && $endTime instanceof \Carbon\Carbon) {
            return $startTime->diffInMinutes($endTime);
        }

        return 0;
    }

    
    private function getImageUrl($imagePath): string
    {
        if (!$imagePath) {
            return '';
        }

        if (filter_var($imagePath, FILTER_VALIDATE_URL)) {
            return $imagePath;
        }

        return asset('storage/' . $imagePath);
    }

    
    protected function calculateETA(Point $from, Booking $booking, ?float $speed = null): ?int
    {
        try {
            $to = $booking->status === 'started' ? $booking->drop_location : $booking->pickup_location;

            $distance = $from->distance($to);

            $distanceKm = $distance / 1000;

            $avgSpeed = $speed ?: 30;

            $timeMinutes = ($distanceKm / $avgSpeed) * 60;

            return (int) round($timeMinutes);
        } catch (\Exception $e) {
            return null;
        }
    }

    
    protected function calculateCurrentDistance(Booking $booking): ?float
    {
        if (!$booking->trip_start_time || $booking->status !== 'started') {
            return null;
        }

        return $booking->estimated_distance;
    }

    
    protected function addStatusMetadata(Booking $booking, string $status, array $metadata): void
    {
        switch ($status) {
            case 'started':
                $booking->update([
                    'trip_start_time' => now(),
                    'actual_pickup_location' => $metadata['pickup_location'] ?? null
                ]);
                break;

            case 'completed':
                $booking->update([
                    'trip_end_time' => now(),
                    'actual_drop_location' => $metadata['drop_location'] ?? null,
                    'actual_duration' => $metadata['actual_duration'] ?? null,
                    'actual_distance' => $metadata['actual_distance'] ?? null
                ]);
                break;

            case 'cancelled':
                $booking->update([
                    'cancelled_at' => now(),
                    'cancellation_reason' => $metadata['reason'] ?? null,
                    'cancelled_by' => $metadata['cancelled_by'] ?? null
                ]);
                break;
        }
    }

    
    public function getNearbyDrivers(Point $location, int $rideTypeId, int $cityId, float $radiusKm = 5): array
    {
        try {
            $drivers = User::whereHas('roles', function ($query) {
                $query->where('name', 'driver');
            })
                ->whereHas('vehicles', function ($query) use ($rideTypeId) {
                    $query->where('ride_type_id', $rideTypeId)
                        ->where('status', 'active');
                })
                ->where('city_id', $cityId)
                ->where('is_online', true)
                ->get();

            $nearbyDrivers = [];

            foreach ($drivers as $driver) {
                $driverLocation = Cache::get("driver_location_{$driver->id}");

                if ($driverLocation) {
                    $driverPoint = new Point($driverLocation['lat'], $driverLocation['lng']);
                    $distance = $location->distance($driverPoint) / 1000; // Convert to km

                    if ($distance <= $radiusKm) {
                        $nearbyDrivers[] = [
                            'driver' => $driver->only(['id', 'name', 'rating']),
                            'vehicle' => $driver->vehicles()
                                ->where('ride_type_id', $rideTypeId)
                                ->where('status', 'active')
                                ->first()
                                ->only(['model', 'number', 'color']),
                            'distance' => round($distance, 2),
                            'eta' => $this->estimateDriverETA($distance),
                            'location' => $driverLocation
                        ];
                    }
                }
            }

            usort($nearbyDrivers, function ($a, $b) {
                return $a['distance'] <=> $b['distance'];
            });

            return $nearbyDrivers;
        } catch (\Exception $e) {
            return [];
        }
    }

    
    protected function estimateDriverETA(float $distanceKm): int
    {
        $avgSpeed = 25;
        $timeMinutes = ($distanceKm / $avgSpeed) * 60;

        return (int) round($timeMinutes);
    }

    /**
     * Check if driver is autogenerated
     * Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
     * 
     * @param User $driver
     * @return bool
     */
    private function isAutogeneratedDriver(User $driver): bool
    {
        if (!$driver->email) {
            return false;
        }

        // Check if email matches pattern: {cityname}driver@etaxi.com
        // Pattern: any characters followed by "driver@etaxi.com"
        $pattern = '/^.+driver@etaxi\.com$/i';
        
        if (preg_match($pattern, $driver->email)) {
            return true;
        }

        return false;
    }
}
