<?php

namespace App\Http\Controllers\Api;

use App\Events\DriverLocationUpdated;
use App\Http\Controllers\Controller;
use App\Models\DriverLocation;
use App\Models\DriverAttendance;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Validator;

class DriverLocationController extends Controller
{
    public function updateLocation(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'latitude' => 'required|numeric|between:-90,90',
                'longitude' => 'required|numeric|between:-180,180',
                'accuracy' => 'nullable|numeric|min:0',
                'speed' => 'nullable|numeric|min:0',
                'heading' => 'nullable|numeric|between:0,360',
                'timestamp' => 'nullable|date',
                'battery_level' => 'nullable|numeric|between:0,100',
                'is_charging' => 'nullable|boolean'
            ]);

            if ($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => 'Validation failed',
                    'errors' => $validator->errors()
                ], 422);
            }

            $driver = Auth::user();

            if ($driver->role_id != 2) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            // 🚫 Autogenerated driver check — HARD STOP
            // Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
            if ($this->isAutogeneratedDriver($driver)) {


                return response()->json([
                    'success' => true,
                    'message' => 'Autogenerated driver location update ignored'
                ], 200);
            }

            // 🚫 Demo driver check — HARD STOP
            $isDemo = false;
            $demoReason = '';

            if ($driver->email && str_ends_with($driver->email, '@etaxi.com')) {
                $isDemo = true;
                $demoReason = 'email_ends_with_etaxi';
            } elseif ($driver->phone && str_starts_with($driver->phone, '999999')) {
                $isDemo = true;
                $demoReason = 'phone_starts_with_999999';
            }
            if ($isDemo) {


                return response()->json([
                    'success' => true,
                    'message' => 'Demo driver location update ignored'
                ], 200);
            }

            $address = $this->getAddressFromCoordinates($request->latitude, $request->longitude);

            $zoneId = $this->getZoneIdFromCoordinates($request->latitude, $request->longitude);

            $locationData = [
                'driver_id' => $driver->id,
                'zone_id' => $zoneId,
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
                'address' => $address,
                'recorded_at' => $request->timestamp ? now()->parse($request->timestamp) : now(),
                'updated_at' => now()
            ];

            $driverLocation = DriverLocation::updateOrCreate(
                ['driver_id' => $driver->id],
                $locationData
            );

            // Update driver_attendance table
            $this->updateDriverAttendance($driver, $request, $address, $zoneId);

            try {
                event(new DriverLocationUpdated($driver, $driverLocation));
            } catch (\Exception $e) {
                // Continue on error
            }

            $toString = function ($value) {
                return is_null($value) ? '' : (string) $value;
            };

            return response()->json([
                'success' => true,
                'message' => 'Location updated successfully',
                'data' => [
                    'location_id' => $toString($driverLocation->id),
                    'zone_id' => $toString($driverLocation->zone_id),
                    'latitude' => $toString($driverLocation->latitude),
                    'longitude' => $toString($driverLocation->longitude),
                    'address' => $toString($driverLocation->address ?? $address),
                    'accuracy' => $toString($driverLocation->accuracy ?? ''),
                    'speed' => $toString($driverLocation->speed ?? ''),
                    'heading' => $toString($driverLocation->heading ?? ''),
                    'battery_level' => $toString($driverLocation->battery_level ?? ''),
                    'is_charging' => $toString($driverLocation->is_charging ?? ''),
                    'recorded_at' => $toString($driverLocation->recorded_at),
                    'updated_at' => $toString($driverLocation->updated_at)
                ]
            ]);
        } catch (\Exception $e) {

            return response()->json([
                'success' => false,
                'message' => 'Internal server error',
                'error' => config('app.debug') ? $e->getMessage() : 'Something went wrong'
            ], 500);
        }
    }

    public function getCurrentLocation()
    {
        try {
            $driver = Auth::user();

            if (!$driver || (!$driver->hasRole('driver') && $driver->role_id !== 2)) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            $currentLocation = $driver->currentLocation;

            if (!$currentLocation) {
                return response()->json([
                    'success' => false,
                    'message' => 'No location data available'
                ], 404);
            }

            return response()->json([
                'success' => true,
                'data' => [
                    'latitude' => $currentLocation->latitude,
                    'longitude' => $currentLocation->longitude,
                    'accuracy' => $currentLocation->accuracy,
                    'speed' => $currentLocation->speed,
                    'heading' => $currentLocation->heading,
                    'battery_level' => $currentLocation->battery_level,
                    'is_charging' => $currentLocation->is_charging,
                    'recorded_at' => $currentLocation->recorded_at,
                    'updated_at' => $currentLocation->updated_at
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Internal server error'
            ], 500);
        }
    }

    public function getLocationHistory(Request $request)
    {
        try {
            $driver = Auth::user();

            if (!$driver || (!$driver->hasRole('driver') && $driver->role_id !== 2)) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            $validator = Validator::make($request->all(), [
                'start_date' => 'nullable|date',
                'end_date' => 'nullable|date|after_or_equal:start_date',
                'limit' => 'nullable|integer|min:1|max:100'
            ]);

            if ($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => 'Validation failed',
                    'errors' => $validator->errors()
                ], 422);
            }

            $query = $driver->locations();

            if ($request->start_date) {
                $query->whereDate('recorded_at', '>=', $request->start_date);
            }

            if ($request->end_date) {
                $query->whereDate('recorded_at', '<=', $request->end_date);
            }

            $locations = $query
                ->orderBy('recorded_at', 'desc')
                ->limit($request->limit ?? 50)
                ->get();

            return response()->json([
                'success' => true,
                'data' => [
                    'locations' => $locations->map(function ($location) {
                        return [
                            'latitude' => $location->latitude,
                            'longitude' => $location->longitude,
                            'accuracy' => $location->accuracy,
                            'speed' => $location->speed,
                            'heading' => $location->heading,
                            'recorded_at' => $location->recorded_at
                        ];
                    }),
                    'total' => $locations->count()
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Internal server error'
            ], 500);
        }
    }

    public function bulkUpdateLocation(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'locations' => 'required|array|min:1|max:100',
                'locations.*.latitude' => 'required|numeric|between:-90,90',
                'locations.*.longitude' => 'required|numeric|between:-180,180',
                'locations.*.timestamp' => 'required|date',
                'locations.*.accuracy' => 'nullable|numeric|min:0',
                'locations.*.speed' => 'nullable|numeric|min:0',
                'locations.*.heading' => 'nullable|numeric|between:0,360'
            ]);

            if ($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => 'Validation failed',
                    'errors' => $validator->errors()
                ], 422);
            }

            $driver = Auth::user();

            if (!$driver || (!$driver->hasRole('driver') && $driver->role_id !== 2)) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            // 🚫 Autogenerated driver check — HARD STOP
            // Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
            if ($this->isAutogeneratedDriver($driver)) {

                return response()->json([
                    'success' => false,
                    'message' => 'Autogenerated driver cannot update location'
                ], 200);
            }

            // Check if demo driver - block location update early to avoid unnecessary processing
            // Demo drivers are identified by:
            // 1. Email ending with @etaxi.com
            // 2. Phone starting with 999999 (demo driver pattern)
            $isDemo = false;
            $demoReason = '';

            if ($driver->email && str_ends_with($driver->email, '@etaxi.com')) {
                $isDemo = true;
                $demoReason = 'email_ends_with_etaxi';
            } elseif ($driver->phone && str_starts_with($driver->phone, '999999')) {
                $isDemo = true;
                $demoReason = 'phone_starts_with_999999';
            }

            if ($isDemo) {

                return response()->json([
                    'success' => false,
                    'message' => 'Demo driver cannot update location'
                ], 200);
            }

            $locations = collect($request->locations)->map(function ($location) use ($driver) {
                return [
                    'driver_id' => $driver->id,
                    'latitude' => $location['latitude'],
                    'longitude' => $location['longitude'],
                    'accuracy' => $location['accuracy'] ?? null,
                    'speed' => $location['speed'] ?? null,
                    'heading' => $location['heading'] ?? null,
                    'recorded_at' => now()->parse($location['timestamp']),
                    'updated_at' => now()
                ];
            });

            DriverLocation::insert($locations->toArray());

            $latestLocation = $locations->sortByDesc('recorded_at')->first();
            $driver->update(['last_location_update' => now()]);


            return response()->json([
                'success' => true,
                'message' => 'Bulk location update completed',
                'data' => [
                    'locations_updated' => $locations->count(),
                    'latest_location' => [
                        'latitude' => $latestLocation['latitude'],
                        'longitude' => $latestLocation['longitude'],
                        'recorded_at' => $latestLocation['recorded_at']
                    ]
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Internal server error'
            ], 500);
        }
    }

    private function getAddressFromCoordinates($latitude, $longitude)
    {
        try {
            if (config('services.google_maps.api_key')) {
                $address = $this->getAddressFromGoogleMaps($latitude, $longitude);
                if ($address) {
                    return $address;
                }
            }

            $address = $this->getAddressFromOpenStreetMap($latitude, $longitude);
            if ($address) {
                return $address;
            }

            return "{$latitude}, {$longitude}";
        } catch (\Exception $e) {
            // Log error silently
            return "{$latitude}, {$longitude}";
        }
    }

    private function getAddressFromGoogleMaps($latitude, $longitude)
    {
        try {
            $apiKey = config('services.google_maps.api_key');
            $latitude = (float) $latitude;
            $longitude = (float) $longitude;

            // Defensive guard to avoid malformed/unsafe URL construction.
            if ($latitude < -90 || $latitude > 90 || $longitude < -180 || $longitude > 180) {
                return null;
            }

            $query = http_build_query([
                'latlng' => $latitude . ',' . $longitude,
                'key' => (string) $apiKey,
            ]);
            $url = 'https://maps.googleapis.com/maps/api/geocode/json?' . $query;

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_TIMEOUT, 10);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            if (defined('CURLOPT_PROTOCOLS')) {
                curl_setopt($ch, CURLOPT_PROTOCOLS, CURLPROTO_HTTPS);
            }

            $response = curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);

            if ($httpCode === 200 && $response) {
                $data = json_decode($response, true);

                if (isset($data['results'][0]['formatted_address'])) {
                    $address = $data['results'][0]['formatted_address'];

                    $addressComponents = $data['results'][0]['address_components'];
                    $city = '';
                    $state = '';
                    $country = '';

                    foreach ($addressComponents as $component) {
                        if (in_array('locality', $component['types'])) {
                            $city = $component['long_name'];
                        } elseif (in_array('administrative_area_level_1', $component['types'])) {
                            $state = $component['long_name'];
                        } elseif (in_array('country', $component['types'])) {
                            $country = $component['long_name'];
                        }
                    }

                    if ($city && $state && $country) {
                        return "{$city}, {$state}, {$country}";
                    } elseif ($city && $state) {
                        return "{$city}, {$state}";
                    } elseif ($city) {
                        return $city;
                    } else {
                        return $address;
                    }
                }
            }

            return null;
        } catch (\Exception $e) {
            return null;
        }
    }

    private function getAddressFromOpenStreetMap($latitude, $longitude)
    {
        try {
            $url = "https://nominatim.openstreetmap.org/reverse?format=json&lat={$latitude}&lon={$longitude}&zoom=18&addressdetails=1";

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_USERAGENT, 'eTaxi-App/1.0');
            curl_setopt($ch, CURLOPT_TIMEOUT, 10);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

            $response = curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);

            if ($httpCode === 200 && $response) {
                $data = json_decode($response, true);

                if (isset($data['display_name'])) {
                    $addressParts = explode(', ', $data['display_name']);

                    $city = '';
                    $state = '';
                    $country = '';

                    foreach ($addressParts as $part) {
                        if (empty($city) && !empty($part)) {
                            $city = $part;
                        } elseif (empty($state) && !empty($part) && $part !== $city) {
                            $state = $part;
                        } elseif (empty($country) && !empty($part) && $part !== $city && $part !== $state) {
                            $country = $part;
                            break;
                        }
                    }

                    if ($city && $state && $country) {
                        return "{$city}, {$state}, {$country}";
                    } elseif ($city && $state) {
                        return "{$city}, {$state}";
                    } elseif ($city) {
                        return $city;
                    } else {
                        return $data['display_name'];
                    }
                }
            }

            return null;
        } catch (\Exception $e) {
            return null;
        }
    }

    private function getZoneIdFromCoordinates($latitude, $longitude)
    {
        try {
            $address = $this->getAddressFromCoordinates($latitude, $longitude);

            if (!$address) {

                return null;
            }

            $cityName = $this->extractCityNameFromAddress($address);

            if (!$cityName) {

                return null;
            }



            $city = \App\Models\City::whereRaw('LOWER(name) LIKE ?', ['%' . strtolower($cityName) . '%'])
                ->orWhereRaw('LOWER(name) LIKE ?', ['%' . strtolower($cityName) . '%'])
                ->first();

            if (!$city) {

                return null;
            }



            $zone = \App\Models\Zone::active()
                ->where('city_id', $city->id)
                ->first();

            if ($zone) {

                return $zone->id;
            }


            return null;
        } catch (\Exception $e) {
            // Log error silently
            return null;
        }
    }

    private function extractCityNameFromAddress($address)
    {
        $cityPatterns = [
            'Mumbai',
            'Bombay',
            'Delhi',
            'Bangalore',
            'Bengaluru',
            'Chennai',
            'Madras',
            'Kolkata',
            'Calcutta',
            'Hyderabad',
            'Pune',
            'Ahmedabad',
            'Surat',
            'Jaipur',
            'Lucknow',
            'Kanpur',
            'Nagpur',
            'Indore',
            'Thane',
            'Bhopal',
            'Visakhapatnam',
            'Pimpri-Chinchwad',
            'Patna',
            'Vadodara',
            'Ghaziabad',
            'Ludhiana',
            'Agra',
            'Nashik',
            'Faridabad',
            'Meerut',
            'Rajkot',
            'Kalyan-Dombivali',
            'Vasai-Virar',
            'Varanasi',
            'Srinagar',
            'Aurangabad',
            'Dhanbad',
            'Amritsar',
            'Allahabad',
            'Ranchi',
            'Howrah',
            'Coimbatore',
            'Jabalpur',
            'Gwalior',
            'Vijayawada',
            'Jodhpur',
            'Madurai',
            'Raipur',
            'Kota',
            'Guwahati',
            'Chandigarh'
        ];

        foreach ($cityPatterns as $city) {
            if (stripos($address, $city) !== false) {
                return $city;
            }
        }

        $parts = explode(',', $address);
        if (count($parts) >= 2) {
            $potentialCity = trim($parts[1] ?? $parts[0]);
            if (!empty($potentialCity) && strlen($potentialCity) > 2) {
                return $potentialCity;
            }
        }

        return null;
    }

    private function updateDriverAttendance($driver, $request, $address, $zoneId)
    {
        try {
            // Get or create active attendance record for today
            $attendance = DriverAttendance::where('driver_id', $driver->id)
                ->where('date', now()->toDateString())
                ->whereNull('offline_time')
                ->latest('online_time')
                ->first();

            // Prepare meta_data with location information
            $metaData = [
                'device_info' => $request->input('device_info'),
                'app_version' => $request->input('app_version'),
                'location' => [
                    'latitude' => $request->latitude,
                    'longitude' => $request->longitude,
                    'address' => $address,
                    'zone_id' => $zoneId,
                    'accuracy' => $request->input('accuracy'),
                    'speed' => $request->input('speed'),
                    'heading' => $request->input('heading'),
                    'battery_level' => $request->input('battery_level'),
                    'is_charging' => $request->input('is_charging'),
                    'timestamp' => now()->toIso8601String(),
                ],
            ];

            if ($attendance) {
                // Update existing attendance record with latest location in meta_data
                $existingMetaData = $attendance->meta_data ?? [];
                $existingMetaData['location'] = $metaData['location'];
                if (isset($metaData['device_info'])) {
                    $existingMetaData['device_info'] = $metaData['device_info'];
                }
                if (isset($metaData['app_version'])) {
                    $existingMetaData['app_version'] = $metaData['app_version'];
                }

                // Update meta_data and touch the updated_at timestamp
                $attendance->meta_data = $existingMetaData;
                $attendance->save();
            } else {
                // Create new attendance record if driver is online but no active session exists
                DriverAttendance::create([
                    'driver_id' => $driver->id,
                    'online_time' => now(),
                    'date' => now()->toDateString(),
                    'meta_data' => $metaData,
                ]);
            }
        } catch (\Exception $e) {
            // Log error silently
        }
    }

    /**
     * Check if driver is autogenerated
     * Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
     *
     * @param User $driver
     * @return bool
     */
    private function isAutogeneratedDriver(User $driver): bool
    {
        if (!$driver->email) {
            return false;
        }

        // Check if email matches pattern: {cityname}driver@etaxi.com
        // Pattern: any characters followed by "driver@etaxi.com"
        $pattern = '/^.+driver@etaxi\.com$/i';

        if (preg_match($pattern, $driver->email)) {
            return true;
        }

        return false;
    }
}
