<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\DriverLocation;
use App\Services\DriverAutoLocationService;
use App\Events\DriverLocationAutoUpdate;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class DriverLocationWebSocketController extends Controller
{
    protected $driverAutoLocationService;

    public function __construct(DriverAutoLocationService $driverAutoLocationService)
    {
        $this->driverAutoLocationService = $driverAutoLocationService;
    }


    public function updateLocationWithWebSocket(Request $request): JsonResponse
    {
        try {
            $validator = Validator::make($request->all(), [
                'latitude' => 'required|numeric|between:-90,90',
                'longitude' => 'required|numeric|between:-180,180',
                'heading' => 'nullable|numeric|between:0,360',
                'speed' => 'nullable|numeric|min:0',
                'accuracy' => 'nullable|numeric|min:0',
                'battery_level' => 'nullable|integer|between:0,100',
                'is_charging' => 'nullable|boolean',
                'timestamp' => 'nullable|date',
                'auto_update' => 'nullable|boolean' // Flag to indicate if this is an auto update
            ]);

            if ($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => 'Validation failed',
                    'errors' => $validator->errors()
                ], 422);
            }

            $driver = Auth::user();

            if ($driver->role_id !== 2) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            // 🚫 Autogenerated driver check — HARD STOP
            // Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
            if ($this->isAutogeneratedDriver($driver)) {

                return response()->json([
                    'success' => true,
                    'message' => 'Autogenerated driver location update ignored'
                ], 200);
            }

            if (!$driver->is_online) {
                return response()->json([
                    'success' => false,
                    'message' => 'Driver must be online to update location'
                ], 400);
            }

            $locationData = [
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
                'heading' => $request->heading ?? 0,
                'speed' => $request->speed ?? 0,
                'accuracy' => $request->accuracy ?? 10,
                'battery_level' => $request->battery_level ?? 80,
                'is_charging' => $request->is_charging ?? false,
                'timestamp' => $request->timestamp ? now()->parse($request->timestamp) : now(),
                'auto_update' => $request->input('auto_update', false)
            ];

            $driverLocation = $this->updateDriverLocationInDatabase($driver, $locationData);

            if ($driverLocation) {
                event(new DriverLocationAutoUpdate($driver, $driverLocation));

                $this->driverAutoLocationService->storeRealtimeLocation($driver, $locationData);

                DB::table('users')
                    ->where('id', $driver->id)
                    ->update([
                        'last_latitude' => $request->latitude,
                        'last_longitude' => $request->longitude,
                        'last_location_at' => now(),
                    ]);



                return response()->json([
                    'success' => true,
                    'message' => 'Location updated and broadcasted successfully',
                    'data' => [
                        'location_id' => $driverLocation->id,
                        'latitude' => $driverLocation->latitude,
                        'longitude' => $driverLocation->longitude,
                        'heading' => $driverLocation->heading,
                        'speed' => $driverLocation->speed,
                        'accuracy' => $driverLocation->accuracy,
                        'battery_level' => $driverLocation->battery_level,
                        'is_charging' => $driverLocation->is_charging,
                        'address' => $driverLocation->address,
                        'zone_id' => $driverLocation->zone_id,
                        'recorded_at' => $driverLocation->recorded_at,
                        'updated_at' => $driverLocation->updated_at
                    ],
                    'websocket_broadcasted' => true,
                    'timestamp' => now()->timestamp
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Failed to update location in database'
                ], 500);
            }
        } catch (\Exception $e) {

            return response()->json([
                'success' => false,
                'message' => 'Internal server error',
                'error' => config('app.debug') ? $e->getMessage() : 'Something went wrong'
            ], 500);
        }
    }


    public function startAutoLocationUpdates(Request $request): JsonResponse
    {
        try {
            $driver = Auth::user();

            if ($driver->role_id !== 2) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            if (!$driver->is_online) {
                return response()->json([
                    'success' => false,
                    'message' => 'Driver must be online to start auto location updates'
                ], 400);
            }

            $started = $this->driverAutoLocationService->startAutoLocationUpdates($driver);

            if ($started) {
                return response()->json([
                    'success' => true,
                    'message' => 'Auto location updates started successfully',
                    'data' => [
                        'driver_id' => $driver->id,
                        'update_interval' => 10, // seconds
                        'is_active' => true,
                        'started_at' => now()->toISOString()
                    ]
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Failed to start auto location updates'
                ], 500);
            }
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Internal server error'
            ], 500);
        }
    }


    public function stopAutoLocationUpdates(Request $request): JsonResponse
    {
        try {
            $driver = Auth::user();

            if ($driver->role_id !== 2) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            $stopped = $this->driverAutoLocationService->stopAutoLocationUpdates($driver);

            if ($stopped) {
                return response()->json([
                    'success' => true,
                    'message' => 'Auto location updates stopped successfully',
                    'data' => [
                        'driver_id' => $driver->id,
                        'is_active' => false,
                        'stopped_at' => now()->toISOString()
                    ]
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Failed to stop auto location updates'
                ], 500);
            }
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Internal server error'
            ], 500);
        }
    }


    public function getAutoLocationStatus(Request $request): JsonResponse
    {
        try {
            $driver = Auth::user();

            if ($driver->role_id !== 2) {
                return response()->json([
                    'success' => false,
                    'message' => 'Unauthorized. Driver access required.'
                ], 401);
            }

            $cacheKey = "auto_location_driver_{$driver->id}";
            $cacheData = Cache::get($cacheKey);

            $status = [
                'driver_id' => $driver->id,
                'is_online' => $driver->is_online,
                'is_active' => $cacheData ? $cacheData['is_active'] : false,
                'started_at' => $cacheData ? $cacheData['started_at'] : null,
                'last_update' => $cacheData ? $cacheData['last_update'] : null,
                'update_interval' => $cacheData ? $cacheData['update_interval'] : 10,
                'websocket_enabled' => true,
                'timestamp' => now()->timestamp
            ];

            return response()->json([
                'success' => true,
                'data' => $status
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Internal server error'
            ], 500);
        }
    }


    private function updateDriverLocationInDatabase(User $driver, array $locationData): ?DriverLocation
    {
        try {
            // 🚫 Autogenerated driver check — HARD STOP
            if ($this->isAutogeneratedDriver($driver)) {

                return null;
            }

            $driverLocation = DriverLocation::where('driver_id', $driver->id)
                ->where('is_active', true)
                ->first();

            if (!$driverLocation) {
                $driverLocation = new DriverLocation();
                $driverLocation->driver_id = $driver->id;
                $driverLocation->is_active = true;
            }

            $driverLocation->latitude = $locationData['latitude'];
            $driverLocation->longitude = $locationData['longitude'];
            $driverLocation->heading = $locationData['heading'];
            $driverLocation->speed = $locationData['speed'];
            $driverLocation->accuracy = $locationData['accuracy'];
            $driverLocation->battery_level = $locationData['battery_level'];
            $driverLocation->is_charging = $locationData['is_charging'];
            $driverLocation->address = $this->getAddressFromCoordinates(
                $locationData['latitude'],
                $locationData['longitude']
            );
            $driverLocation->recorded_at = $locationData['timestamp'];

            $zone = $this->findZoneForLocation($locationData['latitude'], $locationData['longitude']);
            $driverLocation->zone_id = $zone?->id;

            $driverLocation->save();

            return $driverLocation;
        } catch (\Exception $e) {
            return null;
        }
    }


    private function findZoneForLocation(float $latitude, float $longitude)
    {
        try {
            return null;
        } catch (\Exception $e) {
            return null;
        }
    }


    private function getAddressFromCoordinates(float $latitude, float $longitude): string
    {
        return "Location: {$latitude}, {$longitude}";
    }

    /**
     * Check if driver is autogenerated
     * Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
     *
     * @param User $driver
     * @return bool
     */
    private function isAutogeneratedDriver(User $driver): bool
    {
        if (!$driver->email) {
            return false;
        }

        // Check if email matches pattern: {cityname}driver@etaxi.com
        // Pattern: any characters followed by "driver@etaxi.com"
        $pattern = '/^.+driver@etaxi\.com$/i';

        if (preg_match($pattern, $driver->email)) {
            return true;
        }

        return false;
    }
}
