<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\DriverLocation;
use App\Services\DriverAutoLocationService;
use App\Events\DriverLocationAutoUpdate;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Cache;

class WebSocketLocationController extends Controller
{
    protected $driverAutoLocationService;

    public function __construct(DriverAutoLocationService $driverAutoLocationService)
    {
        $this->driverAutoLocationService = $driverAutoLocationService;
    }

    
    public function handleLocationUpdate(Request $request): JsonResponse
    {
        try {
            $driverId = $request->input('driver_id');
            $driver = User::find($driverId);

            if (!$driver) {

                return response()->json(['error' => 'Driver not found'], 404);
            }

            if ($driver->role_id !== 2) {
                return response()->json(['error' => 'User is not a driver'], 403);
            }

            // 🚫 Autogenerated driver check — HARD STOP
            // Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
            if ($this->isAutogeneratedDriver($driver)) {
                
                return response()->json([
                    'success' => true,
                    'message' => 'Autogenerated driver location update ignored'
                ], 200);
            }

            $request->validate([
                'latitude' => 'required|numeric|between:-90,90',
                'longitude' => 'required|numeric|between:-180,180',
                'heading' => 'nullable|numeric|between:0,360',
                'speed' => 'nullable|numeric|min:0',
                'accuracy' => 'nullable|numeric|min:0',
                'battery_level' => 'nullable|integer|between:0,100',
                'is_charging' => 'nullable|boolean'
            ]);

            $locationData = [
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
                'heading' => $request->heading ?? 0,
                'speed' => $request->speed ?? 0,
                'accuracy' => $request->accuracy ?? 10,
                'battery_level' => $request->battery_level ?? 80,
                'is_charging' => $request->is_charging ?? false,
                'timestamp' => now()->timestamp
            ];

            $driverLocation = $this->updateDriverLocationInDatabase($driver, $locationData);

            if ($driverLocation) {
                event(new DriverLocationAutoUpdate($driver, $driverLocation));

                $this->driverAutoLocationService->storeRealtimeLocation($driver, $locationData);



                return response()->json([
                    'success' => true,
                    'message' => 'Location updated successfully',
                    'location' => $locationData,
                    'driver_id' => $driver->id
                ]);
            } else {
                return response()->json(['error' => 'Failed to update location'], 500);
            }
        } catch (\Exception $e) {
            return response()->json(['error' => 'Failed to update location'], 500);
        }
    }

    
    private function updateDriverLocationInDatabase(User $driver, array $locationData): ?DriverLocation
    {
        try {
            // 🚫 Autogenerated driver check — HARD STOP
            if ($this->isAutogeneratedDriver($driver)) {
                
                return null;
            }



            $driverLocation = DriverLocation::where('driver_id', $driver->id)
                ->where('is_active', true)
                ->first();

            if (!$driverLocation) {
                $driverLocation = new DriverLocation();
                $driverLocation->driver_id = $driver->id;
                $driverLocation->is_active = true;

            } else {

            }

            $driverLocation->latitude = $locationData['latitude'];
            $driverLocation->longitude = $locationData['longitude'];
            $driverLocation->heading = $locationData['heading'];
            $driverLocation->speed = $locationData['speed'];
            $driverLocation->accuracy = $locationData['accuracy'];
            $driverLocation->battery_level = $locationData['battery_level'];
            $driverLocation->is_charging = $locationData['is_charging'];
            $driverLocation->address = $this->getAddressFromCoordinates(
                $locationData['latitude'],
                $locationData['longitude']
            );
            $driverLocation->recorded_at = now();

            $zone = $this->findZoneForLocation($locationData['latitude'], $locationData['longitude']);
            $driverLocation->zone_id = $zone?->id;

            $driverLocation->save();

            $driver->update([
                'last_latitude' => $locationData['latitude'],
                'last_longitude' => $locationData['longitude'],
                'last_location_at' => now(),
            ]);


            return $driverLocation;
        } catch (\Exception $e) {
            return null;
        }
    }

    
    private function findZoneForLocation(float $latitude, float $longitude)
    {
        try {
            return null;
        } catch (\Exception $e) {
            return null;
        }
    }

    
    private function getAddressFromCoordinates(float $latitude, float $longitude): string
    {
        return "Location: {$latitude}, {$longitude}";
    }

    /**
     * Check if driver is autogenerated
     * Autogenerated drivers have email pattern: {cityname}driver@etaxi.com
     * 
     * @param User $driver
     * @return bool
     */
    private function isAutogeneratedDriver(User $driver): bool
    {
        if (!$driver->email) {
            return false;
        }

        // Check if email matches pattern: {cityname}driver@etaxi.com
        // Pattern: any characters followed by "driver@etaxi.com"
        $pattern = '/^.+driver@etaxi\.com$/i';
        
        if (preg_match($pattern, $driver->email)) {
            return true;
        }

        return false;
    }

    
    public function authenticateWebSocket(Request $request): JsonResponse
    {
        try {
            $driverId = $request->input('driver_id');
            $token = $request->input('token');

            $driver = User::where('id', $driverId)
                ->where('bearer_token', $token)
                ->where('role_id', 2)
                ->first();

            if (!$driver) {
                return response()->json(['error' => 'Authentication failed'], 401);
            }

            return response()->json([
                'success' => true,
                'driver_id' => $driver->id,
                'socket_id' => 'ws_' . $driver->id . '_' . time(),
                'channels' => [
                    'private-driver.' . $driver->id,
                    'driver.location.updates',
                    'driver.location.' . $driver->id
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json(['error' => 'Authentication failed'], 500);
        }
    }
}
