<?php

namespace App\Jobs;

use App\Models\Booking;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;

use App\Events\BookingStatusChanged;

class AutoUpdateBookingToStarted implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 1;
    public $timeout = 30;

    protected $booking;

    /**
     * Create a new job instance.
     */
    public function __construct(Booking $booking)
    {
        $this->booking = $booking;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {

        
        try {
            // Refresh booking to get latest status
            $this->booking->refresh();

            // Check if booking is still arrived and has driver assigned
            if ($this->booking->status !== 'arrived' || !$this->booking->driver_id) {

                return;
            }

            // Check if driver is auto-generated driver (only auto-update for auto-generated drivers)
            $city = $this->booking->city;
            if (!$city) {

                return;
            }

            // Extract city name (first part before comma)
            $cityNameParts = explode(',', $city->name);
            $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
            $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

            // Load driver to check email
            $this->booking->load('driver');
            $driver = $this->booking->driver;

            if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                return;
            }

            // Update booking status to started (bypass OTP for auto-generated driver)
            DB::beginTransaction();
            try {
                $this->booking->update([
                    'status' => 'started',
                    'started_at' => now(),
                    'otp_verified_at' => now(), // Mark OTP as verified
                ]);

                DB::commit();



                // Refresh booking to get latest data
                $this->booking->refresh();
                $this->booking->load(['user', 'driver', 'rideType']);

                // Send trip started notification to user (same as normal start)
                // Use NotificationService::tripStarted() method which is used in normal flow
                try {
                    
                    
                    $notificationService = app(\App\Services\NotificationService::class);
                    $bookingForNotification = $this->booking->fresh();
                    $bookingForNotification->load(['user', 'driver', 'rideType']);
                    
                    // Use tripStarted() method (same as normal flow)
                    $notificationService->tripStarted($bookingForNotification);
                    
                    
                } catch (\Exception $e) {
                }

                // Dispatch event (same as normal start)
                event(new BookingStatusChanged(
                    $this->booking->fresh(),
                    'started',
                    'OTP verified successfully, trip started (auto-generated driver)'
                ));

                // Schedule auto-update to 'completed' status after 60 seconds (1 minute trip simulation)
                $delaySeconds = 60;


                \App\Jobs\AutoUpdateBookingToCompleted::dispatch($this->booking->fresh())
                    ->delay(now()->addSeconds($delaySeconds));

            } catch (\Exception $e) {
                DB::rollBack();
                throw $e;
            }

        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Handle a job failure.
     */
    public function failed(\Throwable $exception): void
    {
    }
}
