<?php

namespace App\Jobs;

use App\Models\Booking;
use App\Models\DriverLocation;
use App\Services\NotificationService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;

use App\Events\BookingStatusChanged;
use App\Events\DriverLocationByBookingUpdated;

class AutoUpdateBookingToArrived implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 1;
    public $timeout = 30;

    protected $booking;

    /**
     * Create a new job instance.
     */
    public function __construct(Booking $booking)
    {
        $this->booking = $booking;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {


        try {
            // Refresh booking to get latest status
            $this->booking->refresh();

            // Check if booking is still accepted and has driver assigned
            if ($this->booking->status !== 'accepted' || !$this->booking->driver_id) {

                return;
            }

            // Ensure at least 30 seconds have passed since booking was accepted
            // This gives time for location updates to be sent
            $acceptedAt = $this->booking->updated_at; // When status changed to 'accepted'
            $secondsSinceAccepted = now()->diffInSeconds($acceptedAt);
            $minWaitSeconds = 30;

            if ($secondsSinceAccepted < $minWaitSeconds) {
                $remainingSeconds = $minWaitSeconds - $secondsSinceAccepted;


                // Re-dispatch with remaining delay
                self::dispatch($this->booking->fresh())
                    ->delay(now()->addSeconds($remainingSeconds));
                return;
            }

            // Check if driver is auto-generated driver (only auto-update for auto-generated drivers)
            $city = $this->booking->city;
            if (!$city) {

                return;
            }

            // Extract city name (first part before comma)
            $cityNameParts = explode(',', $city->name);
            $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
            $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

            // Load driver to check email
            $this->booking->load('driver');
            $driver = $this->booking->driver;

            if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                return;
            }

            // Update booking status to arrived (same as normal arrival)
            DB::beginTransaction();
            try {
                // Try to set driver_arrival_time if column exists, otherwise just update status
                try {
                    $this->booking->update([
                        'status' => 'arrived',
                        'driver_arrival_time' => now(),
                    ]);
                } catch (\Exception $e) {
                    // Column doesn't exist, just update status
                    $this->booking->update(['status' => 'arrived']);
                }

                // Update driver location to pickup location when arrived
                if ($this->booking->driver_id && $this->booking->pickup_latitude && $this->booking->pickup_longitude) {
                    $driverLocation = DriverLocation::where('driver_id', $this->booking->driver_id)
                        ->where('is_active', true)
                        ->first();

                    if ($driverLocation) {
                        $driverLocation->update([
                            'latitude' => $this->booking->pickup_latitude,
                            'longitude' => $this->booking->pickup_longitude,
                            'recorded_at' => now(),
                        ]);
                    }

                    // Update driver's last location in users table
                    $this->booking->driver->update([
                        'last_latitude' => $this->booking->pickup_latitude,
                        'last_longitude' => $this->booking->pickup_longitude,
                        'last_location_at' => now(),
                    ]);

                    // Broadcast final location update to pickup
                    event(new DriverLocationByBookingUpdated(
                        $this->booking->id,
                        (float) $this->booking->pickup_latitude,
                        (float) $this->booking->pickup_longitude,
                        $this->booking->driver_id
                    ));
                }

                DB::commit();



                // Refresh booking to get latest data
                $this->booking->refresh();
                $this->booking->load(['user', 'driver']);

                // Send notification to user (same as normal arrival)
                $notificationService = app(NotificationService::class);
                $otp = $this->booking->otp ?: 'N/A';
                $message = 'Your driver has arrived. Please provide otp ' . $otp;
                $notificationService->sendBookingNotificationToUser(
                    $this->booking,
                    'driver_arrived',
                    $message
                );



                // Dispatch event (same as normal arrival)
                event(new BookingStatusChanged(
                    $this->booking->fresh(),
                    'arrived',
                    $message
                ));

                // Schedule auto-update to 'started' status after 10 seconds (bypass OTP for auto-generated driver)
                $delaySeconds = 10;


                \App\Jobs\AutoUpdateBookingToStarted::dispatch($this->booking->fresh())
                    ->delay(now()->addSeconds($delaySeconds));
            } catch (\Exception $e) {
                DB::rollBack();
                throw $e;
            }
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Handle a job failure.
     */
    public function failed(\Throwable $exception): void
    {
        // Handle job failure
    }
}
