<?php

namespace App\Jobs;

use App\Models\Booking;
use App\Models\DriverLocation;
use App\Models\User;
use App\Services\NotificationService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;

use App\Events\BookingStatusChanged;
use App\Events\DriverAssigned;

class AutoAssignToAutoGeneratedDriver implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 1;
    public $timeout = 30;

    protected $booking;

    /**
     * Create a new job instance.
     */
    public function __construct(Booking $booking)
    {
        $this->booking = $booking;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        try {
            // Refresh booking to get latest status
            $this->booking->refresh();

            // Check if booking is still searching/expired and has no driver assigned
            // Allow expired status as API can reset it to searching
            if (!in_array($this->booking->status, ['searching', 'expired']) || $this->booking->driver_id) {

                return;
            }

            // If booking is expired, reset to searching
            if ($this->booking->status === 'expired') {

                $this->booking->update([
                    'status' => 'searching',
                    'expired_at' => null,
                ]);
                $this->booking->refresh();
            }



            // Check if any non-auto-generated driver has accepted
            // Non-auto-generated drivers are those whose email does NOT match pattern {cityname}driver@etaxi.com
            $city = $this->booking->city;
            if (!$city) {

                return;
            }

            // Extract city name (first part before comma)
            $cityNameParts = explode(',', $city->name);
            $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
            $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

            // Check if any non-auto-generated driver has accepted
            // This would be checked by looking at booking status - if it's still 'searching', no one accepted
            // But we also need to check if any driver has been notified and might accept soon
            // For now, we'll just check if booking is still searching without driver_id

            // Find the auto-generated driver for this city
            // For auto-generated drivers, we're more flexible:
            // - Don't require is_online (we'll set it if needed)
            // - Check both users.city_id and driverProfile.city_id
            $autoGeneratedDriver = User::where('email', $autoGeneratedEmailPattern)
                ->where('role_id', 2) // Driver role
                ->where('status', 'active')
                ->where(function ($query) use ($city) {
                    $query->where('city_id', $city->id)
                        ->orWhereHas('driverProfile', function ($q) use ($city) {
                            $q->where('city_id', $city->id);
                        });
                })
                ->first();

            if (!$autoGeneratedDriver) {
                
                return;
            }

            // Ensure auto-generated driver is online (set it if not)
            if (!$autoGeneratedDriver->is_online) {

                $autoGeneratedDriver->update(['is_online' => 1]);
                $autoGeneratedDriver->refresh();
            }

            // Check if auto-generated driver has a running ride
            // For auto-generated drivers, we allow multiple bookings or complete previous booking
            $runningRide = Booking::where('driver_id', $autoGeneratedDriver->id)
                ->whereIn('status', ['accepted', 'arrived', 'started'])
                ->where('id', '!=', $this->booking->id)
                ->first();

            if ($runningRide) {
                // For auto-generated drivers, complete the previous booking if it's in 'accepted' or 'arrived' status
                // This allows the driver to accept new bookings
                if (in_array($runningRide->status, ['accepted', 'arrived'])) {
                    // Complete the previous booking
                    $runningRide->update([
                        'status' => 'completed',
                        'completed_at' => now(),
                        'updated_at' => now()
                    ]);

                    // Clear driver's current booking
                    $autoGeneratedDriver->update([
                        'current_booking_id' => null
                    ]);


                } else {
                    // If status is 'started', we can't complete it - skip this booking
                    return;
                }
            }

            // Check if auto-generated driver has a vehicle matching the ride type
            if ($this->booking->ride_type_id) {
                $hasMatchingVehicle = $autoGeneratedDriver->vehicles()
                    ->where('ride_type_id', $this->booking->ride_type_id)
                    ->where('status', 'active')
                    ->exists();

                if (!$hasMatchingVehicle) {

                    return;
                }
            }

            

            // Auto-assign booking to auto-generated driver
            DB::beginTransaction();
            try {
                $this->booking->update([
                    'driver_id' => $autoGeneratedDriver->id,
                    'status' => 'accepted',
                ]);

                $autoGeneratedDriver->update(['current_booking_id' => $this->booking->id]);

                // Update driver profile availability
                if ($autoGeneratedDriver->driverProfile) {
                    $autoGeneratedDriver->driverProfile->update(['is_available' => false]);
                }

                DB::commit();

                

                // Initialize driver location for location updates (if not exists) - OUTSIDE transaction
                // Use driver's last location or set to a point 2-3 km away from pickup for route simulation
                $driverLocation = DriverLocation::where('driver_id', $autoGeneratedDriver->id)
                    ->where('is_active', true)
                    ->first();

                

                if (!$driverLocation) {
                    // Use driver's last location if available
                    $startLat = $autoGeneratedDriver->last_latitude ?? $this->booking->pickup_latitude;
                    $startLng = $autoGeneratedDriver->last_longitude ?? $this->booking->pickup_longitude;

                    // If driver is at pickup location, move them 2.5 km away for route simulation
                    $pickupLat = (float) $this->booking->pickup_latitude;
                    $pickupLng = (float) $this->booking->pickup_longitude;

                    $distanceToPickup = $this->haversineDistance(
                        (float) $startLat,
                        (float) $startLng,
                        $pickupLat,
                        $pickupLng
                    );

                    if ($distanceToPickup < 0.1) { // Less than 100 meters
                        // Calculate a point 2.5 km away in a random direction
                        $distanceAway = 2.5; // km
                        $randomAngle = deg2rad(rand(0, 360));
                        $earthRadius = 6371; // km

                        $newLat = asin(sin(deg2rad($pickupLat)) * cos($distanceAway / $earthRadius) +
                            cos(deg2rad($pickupLat)) * sin($distanceAway / $earthRadius) * cos($randomAngle));
                        $newLng = deg2rad($pickupLng) + atan2(
                            sin($randomAngle) * sin($distanceAway / $earthRadius) * cos(deg2rad($pickupLat)),
                            cos($distanceAway / $earthRadius) - sin(deg2rad($pickupLat)) * sin($newLat)
                        );

                        $startLat = rad2deg($newLat);
                        $startLng = rad2deg($newLng);
                    }

                    $driverLocation = new DriverLocation();
                    $driverLocation->driver_id = $autoGeneratedDriver->id;
                    $driverLocation->is_active = true;
                    $driverLocation->latitude = $startLat;
                    $driverLocation->longitude = $startLng;
                    $driverLocation->recorded_at = now();
                    $driverLocation->save();

                    // Update driver's last location
                    $autoGeneratedDriver->update([
                        'last_latitude' => $startLat,
                        'last_longitude' => $startLng,
                        'last_location_at' => now(),
                    ]);

                    
                } else {
                    // Driver location exists, but ensure it's not at pickup (for route simulation)
                    $pickupLat = (float) $this->booking->pickup_latitude;
                    $pickupLng = (float) $this->booking->pickup_longitude;
                    $currentLat = (float) $driverLocation->latitude;
                    $currentLng = (float) $driverLocation->longitude;

                    $distanceToPickup = $this->haversineDistance($currentLat, $currentLng, $pickupLat, $pickupLng);

                    if ($distanceToPickup < 0.1) { // Less than 100 meters
                        // Move driver 2.5 km away for route simulation
                        $distanceAway = 2.5; // km
                        $randomAngle = deg2rad(rand(0, 360));
                        $earthRadius = 6371; // km

                        $newLat = asin(sin(deg2rad($pickupLat)) * cos($distanceAway / $earthRadius) +
                            cos(deg2rad($pickupLat)) * sin($distanceAway / $earthRadius) * cos($randomAngle));
                        $newLng = deg2rad($pickupLng) + atan2(
                            sin($randomAngle) * sin($distanceAway / $earthRadius) * cos(deg2rad($pickupLat)),
                            cos($distanceAway / $earthRadius) - sin(deg2rad($pickupLat)) * sin($newLat)
                        );

                        $startLat = rad2deg($newLat);
                        $startLng = rad2deg($newLng);

                        $driverLocation->update([
                            'latitude' => $startLat,
                            'longitude' => $startLng,
                            'recorded_at' => now(),
                        ]);

                        $autoGeneratedDriver->update([
                            'last_latitude' => $startLat,
                            'last_longitude' => $startLng,
                            'last_location_at' => now(),
                        ]);

                    } else {
                    }
                }

                // Refresh booking to get latest data
                $this->booking->refresh();
                $this->booking->load(['user', 'driver']);

                

                // Dispatch events (same as normal acceptance)
                // DriverAssigned event for socket broadcast
                event(new DriverAssigned($this->booking->fresh(), $autoGeneratedDriver));

                // BookingStatusChanged event for status update
                event(new BookingStatusChanged(
                    $this->booking->fresh(),
                    'accepted',
                    'Booking accepted successfully - Driver is on the way'
                ));

                // Schedule auto-update to 'arrived' status after 30 seconds
                // This gives time for location updates to be sent every 2 seconds
                $delaySeconds = 30;


                \App\Jobs\AutoUpdateBookingToArrived::dispatch($this->booking->fresh())
                    ->delay(now()->addSeconds($delaySeconds));
            } catch (\Exception $e) {
                DB::rollBack();
                throw $e;
            }
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Handle a job failure.
     */
    public function failed(\Throwable $exception): void
    {
    }

    /**
     * Calculate distance between two points using Haversine formula
     */
    private function haversineDistance(float $lat1, float $lon1, float $lat2, float $lon2): float
    {
        $earthRadius = 6371; // km

        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);

        $a = sin($dLat / 2) * sin($dLat / 2)
            + cos(deg2rad($lat1)) * cos(deg2rad($lat2))
            * sin($dLon / 2) * sin($dLon / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c;
    }
}
