<?php

namespace App\Jobs;

use App\Models\Booking;
use App\Models\Transaction;
use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;

use App\Events\BookingStatusChanged;
use App\Services\UserDebtService;
use App\Services\NotificationService;

class AutoUpdateBookingToCompleted implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 1;
    public $timeout = 60;

    protected $booking;

    /**
     * Create a new job instance.
     */
    public function __construct(Booking $booking)
    {
        $this->booking = $booking;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {


        try {
            // Refresh booking to get latest status
            $this->booking->refresh();

            // Check if booking is still started and has driver assigned
            if ($this->booking->status !== 'started' || !$this->booking->driver_id) {

                return;
            }

            // Check if driver is auto-generated driver (only auto-update for auto-generated drivers)
            $city = $this->booking->city;
            if (!$city) {

                return;
            }

            // Extract city name (first part before comma)
            $cityNameParts = explode(',', $city->name);
            $cityName = strtolower(str_replace(' ', '', trim($cityNameParts[0])));
            $autoGeneratedEmailPattern = "{$cityName}driver@etaxi.com";

            // Load driver to check email
            $this->booking->load('driver');
            $driver = $this->booking->driver;

            if (!$driver || $driver->email !== $autoGeneratedEmailPattern) {
                return;
            }

            DB::beginTransaction();
            try {
                // Calculate actual distance and duration (use estimated if actual not available)
                $actualDistance = $this->booking->actual_distance ?? $this->booking->estimated_distance ?? 0;
                $actualDuration = $this->booking->actual_duration ?? $this->booking->estimated_duration ?? 0;

                // If started_at exists, calculate duration from start time
                if ($this->booking->started_at) {
                    $actualDuration = $this->booking->started_at->diffInMinutes(now());
                }

                // Update booking status to completed
                $this->booking->update([
                    'status' => 'completed',
                    'completed_at' => now(),
                    'actual_distance' => $actualDistance,
                    'actual_duration' => $actualDuration,
                ]);

                // Refresh booking before fare calculation
                $this->booking->refresh();

                // Calculate and update fare (same as normal completion)
                $driverBookingController = app(\App\Http\Controllers\Api\DriverBookingController::class);
                $reflection = new \ReflectionClass($driverBookingController);

                // Call calculateAndUpdateFare method
                if ($reflection->hasMethod('calculateAndUpdateFare')) {
                    $calculateFareMethod = $reflection->getMethod('calculateAndUpdateFare');
                    $calculateFareMethod->setAccessible(true);
                    $calculateFareMethod->invoke($driverBookingController, $this->booking->fresh());
                }

                // Process trip completion (creates commission, wallet transactions, etc.)
                if ($reflection->hasMethod('processTripCompletion')) {
                    $processTripMethod = $reflection->getMethod('processTripCompletion');
                    $processTripMethod->setAccessible(true);
                    $processTripMethod->invoke($driverBookingController, $this->booking->fresh());
                }

                // Refresh booking after fare calculation
                $this->booking->refresh();

                // Process payment and update payment_status to 'paid' for all payment methods
                $bookingForPayment = $this->booking->fresh();
                $paymentMethod = $bookingForPayment->payment_method ?? 'cash';
                $currentPaymentStatus = $bookingForPayment->payment_status ?? 'pending';



                if ($paymentMethod === 'cash') {

                    $this->processCashPayment($bookingForPayment, $driver);

                    // Verify cash payment processed
                    $bookingForPayment->refresh();
                } else {
                    // For non-cash payments, just update payment_status to 'paid'


                    // Use DB::table to ensure update happens
                    $updated = DB::table('bookings')
                        ->where('id', $bookingForPayment->id)
                        ->update([
                            'payment_status' => 'paid',
                            'updated_at' => now(),
                        ]);



                    // Verify the update
                    $bookingForPayment->refresh();


                    if ($bookingForPayment->payment_status !== 'paid') {
                    } else {
                    }
                }

                // Clear driver's current booking
                $driver->update(['current_booking_id' => null]);

                // Update driver profile availability
                if ($driver->driverProfile) {
                    $driver->driverProfile->update(['is_available' => true]);
                }

                DB::commit();



                // Refresh booking to get latest data
                $this->booking->refresh();
                $this->booking->load(['user', 'driver', 'rideType']);

                // Send trip completed notification to user (same as normal completion)
                try {
                    $notificationService = app(\App\Services\NotificationService::class);
                    $notificationService->tripCompleted($this->booking->fresh());
                } catch (\Exception $e) {
                }

                // Dispatch event (same as normal completion)
                event(new BookingStatusChanged(
                    $this->booking->fresh(),
                    'completed',
                    'Trip completed successfully (auto-generated driver)'
                ));
            } catch (\Exception $e) {
                DB::rollBack();
                throw $e;
            }
        } catch (\Exception $e) {
            throw $e;
        }
    }

    /**
     * Process cash payment for auto-generated driver
     */
    private function processCashPayment(Booking $booking, User $driver): void
    {
        try {


            // Get booking total amount
            $amount = (float) ($booking->total_amount ?? 0);
            $tipAmount = (float) ($booking->tip_amount ?? 0);
            $totalAmount = $amount + $tipAmount;

            if ($totalAmount <= 0) {

                return;
            }

            // Create transaction (similar to initTransaction for cash)
            $transaction = Transaction::create([
                'transaction_id' => 'TXN_' . time() . '_' . rand(1000, 9999),
                'wallet_id' => null,
                'booking_id' => $booking->id,
                'user_id' => $booking->user_id,
                'type' => 'payment',
                'amount' => $totalAmount,
                'balance' => 0,
                'currency' => 'INR',
                'payment_method' => 'cash',
                'status' => 'completed', // Directly mark as completed for auto-generated driver
                'description' => "Payment for ride #{$booking->booking_code}",
                'gateway_transaction_id' => null,
                'gateway_response' => [
                    'driver_id' => $driver->id,
                    'driver_name' => $driver->name,
                    'updated_at' => now()->toISOString(),
                    'status' => 'completed',
                    'auto_processed' => true,
                ],
                'meta_data' => [
                    'booking_code' => $booking->booking_code,
                    'user_id' => $booking->user_id,
                    'driver_id' => $driver->id,
                    'tip_amount' => $tipAmount,
                    'fare_amount' => $amount,
                    'auto_processed' => true,
                ],
            ]);

            // Update booking payment status using DB::table to ensure database update
            $updatedRows = DB::table('bookings')
                ->where('id', $booking->id)
                ->update([
                    'payment_status' => 'paid',
                    'payment_method' => 'cash',
                    'online_paid_amount' => 0,
                    'updated_at' => now(),
                ]);



            // Refresh booking model to get updated values
            $booking->refresh();

            // Settle debts when payment is received
            try {
                app(UserDebtService::class)->settleAppliedDebtsForBooking($booking->fresh());
            } catch (\Exception $e) {
                // Log error silently
            }

            // Credit debt amount to admin wallet when payment is received
            try {
                $paymentController = app(\App\Http\Controllers\Api\PaymentController::class);
                if (method_exists($paymentController, 'creditDebtAmountToAdminWallet')) {
                    $paymentController->creditDebtAmountToAdminWallet($booking->fresh());
                }
            } catch (\Exception $e) {
                // Log error silently
            }

            // Send payment completion notification to driver
            try {
                app(NotificationService::class)->sendPaymentCompletionNotificationToDriver($booking->fresh());
            } catch (\Exception $e) {
            }
        } catch (\Exception $e) {
            // Don't throw - allow booking to complete even if payment processing fails
        }
    }

    /**
     * Handle a job failure.
     */
    public function failed(\Throwable $exception): void
    {
        // Handle job failure
    }
}
